### PR TITLE
Tweak bursting

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

There is now 60 seconds before a larva autobursts. It now also doesn't eat into the original burst time, and is instead added onto it.

It properly sets the stage to stage 6 when the larva spawns. The larva can now move to instantly burst instead of waiting out the timer.

## Why / Balance

CM-13 parity.

## Technical details

Evo system now checks for a burster component and doesn't give points if found. This burster component is also checked for movement to burst the target, and is removed upon bursting.

InputMoveEvent on the burster component will burst the victim instantly. Rotting will also make autobursting happen.

Some cleanup was done to remove redundancy. Some other notes:
There is a seperate countdown for a larva autobursting and when a player takes them. The first is about 60 seconds and the second is 20. Leaving it at 60 for now until that's implemented in (probably with queue).

Also prevent evolving while in a container, for obvious reasons.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/e18f5d8c-0fa8-44ad-ae3e-68126d5fefe5

## Breaking changes

**Changelog**

:cl:
- fix: Larva auto-burst time has been upped to 60 (from 20) seconds
- fix: Larva can now move to burst immediately from their host

### CODE REVIEW

**Review by Dutch-VanDerLinde — APPROVED** [review]

**Comment by Vermidia** [comment]
Removed the evo point blocker - tested in cm-13 and they seem to gain points fine while in a victim.

**Comment by Dutch-VanDerLinde** [comment]
> Removed the evo point blocker - tested in cm-13 and they seem to gain points fine while in a victim.

can they evolve while in a victim

**Comment by Vermidia** [comment]
Ahh, yeah they can't. They need to be on a turf. I believe being in a container counters here.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
