### PR TITLE
Add Healer drone strain

### LINKED ISSUE #271: Healer drone
- [x] #272
- [ ] #273
- [ ] #274

### LINKED ISSUE #273: Healer drone prototype

### LINKED ISSUE #274: Healer drone abilities
- [x] #364 
- [x] #365 
- [x] #366
- [x] #367 
- [x] #368 
- [x] #369 
- [x] #377
- [x] #370 
- [ ] #378 (improved)
- [ ] #422
- [ ] #423 (lesser)

### LINKED ISSUE #422: Apply salve

### PR DESCRIPTION
**Pull request by blueDev2**
## About the PR

Cm13 parity

Resolves #271 
Resolves #273
Resolves #274
Resolves #422

## Media

https://github.com/user-attachments/assets/d4438d40-b1e8-43d8-9828-938bd81c72ea

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: blueDev2
- add: Added Healer, a drone strain that can use up it's own health to heal allied xenos. They can also instantly sacrifice themselves to heal an allied xeno by 75% of their current health.

### CODE REVIEW

**Review by SolidusSnek — CHANGES_REQUESTED** [review]
Minor spelling fixes.

**Comment by IceStormtheDragon** [comment]
Hows this PR going? Curious since im excited to have this in game and  to be able to play as.

**Comment by blueDev2** [comment]
> Hows this PR going? Curious since im excited to have this in game and to be able to play as.

To my understanding, it should be done. I am waiting approval.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
