### PR TITLE
Rotting now shows permently deceased on health scanner

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Title.

## Why / Balance

CM-parity. Not sure if there's any other conditions that also show this and prevent revival (like decaps), but this should be all the implemented ones.

## Media

ded

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed the health analyzer not showing permanently dead on rotted corpses
- tweak: Permanently dead and holocards on the analyzer are now colorful.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
Can you make the text red or something when they're permadead cuz it took me like 4 seconds to actually find the permadead text

**Comment by Vermidia** [comment]
yeah, I think in cm they bar is colored, I can modify it a bit

**Comment by Dutch-VanDerLinde** [comment]
or possibly even something even more obvious like theres a big ass text in front saying "PATIENT IS PERMENATLY DECEASED" and the rest of the analyzer is darkened

**Comment by Vermidia** [comment]
living
Added colors to decreased and holocard tags on the analyzer, also shortened all the texts and made them more inline with their cm descs.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
