### PR TITLE
Parasite AI 2

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Basically am making the parasites even more like cm with their AI.
Requires #4042
Current features:
- [X] AI parasites cannibalize eachother if more than 2 are around eachother
- [X] AI parasites can't be pulled
- [X] Player parasites can't be picked up (and can escape pickups)
- [X] ~~Parasites can't be thrown by hand, and~~ eggs can't be thrown at all
- [X] AI Parasites die after 30 seconds if not carried by a carrier
- [X] AI Parasites have forced Idle time after being picked up/dropped/removed from eggs/resinholes
- [X] AI Parasites only go into eggs/resin holes/eggmorph (not yet) when about to die from time
- [X] Leap and infect idles changed to 5 seconds exactly 
- [X] Chance to go idle after successful leaps/infects
- [X] AI Parasites can successfully infect from leaps up to 3 tiles away
- [X] Parasites die if they do 2 successful infects/leaps
- [X] Idle time refreshes jumps
- [X] Separate AI into dying and active compounds
- [X] Xenos can examine AI parasites to know if they're active, idle, or dying
- [X] Parasites can join from carriers if over carrier's reserve
- [X] Add doafter to placing eggs
  - [X] Doafter is 3.5 seconds for most, 2.5 for drones (not lessers) and 1.0 for carriers
 - [X] Egg placing sound
 - [X] Bugfix carrier
 - [X] Add sounds to resin hole actions

## Why / Balance

parity

## Technical details

Parasite AI Stuff put into it's own file, both are still SharedParasiteSystem. Added ParasiteAI Comp for systems to differentiate player controlled vs not parasites

Update now goes through all parasite AI to update their times in the AI system. The AI system handles the mode changes of the parasite. To change the AI tasks for dying vs active, the Server version of the system is used. EggSystem had it's canPlaceEgg stuff separated out so it can be checked before and after the doafter. Added some blockDuplicates to the infect and egg doafters for parity. Egg checks user's plasma for placing eggs now (costs 30)

AI was modified by separating active vs dying behaviors. Dying no longer has any waits to it. When AI parasites try to die they'll check if open eggs are around and if so don't.

Due note the range checked for egg checking is higher than cm, since it's using interact range. Cannibalization uses a smaller range since it's to prevent tile stacking mainly.

The EggRoleSystem has been generized, as carrier now uses it. I mostly left the base carrier systems as they were, and just fixed up any bugs/missing features, and added sounds and such. I had to rework the reserve UI quite a bit until I figured why it wasn't working but it also works fine now too.

There's a bit of leeway with how I did throw/dropping parasites on death, the latter to stop instant cannibalization of all paras nearby. Throw was made so the parasite is active but still stunned for the 5 second duration, but it means they'll instantly be ready for leaping action afterward.

Another not technically parity is that parasites die after attempting 2 leaps (no matter if they succeed) while activate, usually resulting them in just dying in 10 seconds without doing much. I could've ported this by just having a 10 second time to die aswell, but I think with the differences in how they function it shouldn't matter much.

I probably missed something since a lot was messed with but most carrier-related thing should be working properly.

## Media

https://github.com/user-attachments/assets/eb165d0d-044e-4a3b-82f6-27d9006644a3

https://github.com/user-attachments/assets/f44b805e-57d4-4545-a264-67c2d2de1693

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: AI Parasites now have periods of Idleness (indicated by resting) and Activeness (indicated by not resting). Parasites will only leap/infect while active.
- fix: AI Parasites die after 30 seconds if not picked up by a carrier. Doing this also resets the timer, and it doesn't progress while carried by them.
- tweak: Egg placing now has sounds, and speed is 3.5 seconds, with normal drones doing it in 2.5 and carriers in 1. It costs 30 plasma to place an egg.
- add: Parasites can go into resin traps to fill them manually. AI paras will do this if they can't get into an egg.
- add: Resin traps can be filled with corrosive acid
- add: Almost all xeno announcements for deaths/trap triggers give location.
- fix: Fixed prae's acid having the boiler spray sprite
- fix: AI parasites will eat eachother if too many are close by
- fix: AI parasite's leaps will infect from farther away
- tweak: Moved carrier's egg and parasite count to examine
- tweak: Made some carrier ability descriptions more informative
- fix: Different acid sprays now dissapate at different rates, with strong acid taking 2 seconds and weak taking the original 0.6
- fix: Praetorian's plasma cost for spray acid is higher. Warden strain's cost even more, and has a slightly longer cooldown
- add: Hives get 1 free carrier slot
- add: Ghosts can join as parasites from carriers
- fix: Parasites won't become AI controlled until 7 minutes have past since the player disconnected
- tweak: Throwing a parasite always makes them able to attempt leaps after the 5 second stun
- fix: Player parasites can't be picked up, and can escape if they are. AI parasites can't be pulled
- tweak: AI Parasites now prioritize downed targets, and don't need line of sight for leaps/infects
- tweak: Carriers dropping eggs/parasites on death is more satisfying
- fix: Item eggs won't show the become parasite verb

### CODE REVIEW

**Comment by Kadeo64** [comment]
> AI parasites cannibalize eachother if more than 2 are around eachother

xruelty...

**Comment by Dutch-VanDerLinde** [comment]
Why do they cannibalize each other

**Comment by Kadeo64** [comment]
> Why do they cannibalize each other

to prevent stacking a bunch of parasites on one tile, I assume. probably added by a cm13 coder forever ago who wasn't intending for people to try and parity their mechanics on a pixelmovement engine

**Comment by Vermidia** [comment]
All the non-carrier related features are done, just need the carrier PR itself now to finish up.

**Comment by Vermidia** [comment]
It's all done for the most part I think...whew. Carriers been bugfixed, game juice has been added. I think I covered all the bases I set out to (If something's missing it's cause I forgot about it). Carrier works, resin traps seem to work fine, parasites be parasiting.

**Comment by DrSmugleaf** [comment]
Test fail is real for once
```
  Failed UninitializedSaveTest [22 s]
  Error Message:
   Prototype XenoResinHole modifies component on spawn: Physics. Modified yaml:
bodyType: Static
```

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR holy shit that's a lot of code

**Pull request merged**
