### PR TITLE
Fix RUNLinter error

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

^^^
title

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
datafield strings are obselete, in the yml: do this
cAS
oB

**Comment by Tunguso4ka** [comment]
> datafield strings are obselete, in the yml: do this cAS oB

i know, it just looks bad.

**Comment by Dutch-VanDerLinde** [comment]
what does CAS and OB mean?? maybe make it full word

**Comment by Tunguso4ka** [comment]
> what does CAS and OB mean?? maybe make it full word

close air support and orbital bombardment 

from <https://cm-ss13.com/wiki/Slang>

**Review by DrSmugleaf — APPROVED** [review]
ty

**Pull request merged**
