### PR TITLE
Larva now transfers control to the burst victim

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## Why / Balance
CM13 parity

also more forgiving for marines who were captured, as they aren't round removed

## Media

https://github.com/user-attachments/assets/11955401-1d00-42c3-9881-e8642402529b

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Bursted larvas will now be under control of the burst victim.

### CODE REVIEW

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
13 deals with this through the xeno queue, which the infected marine and parasite get put to the front of I think
Does this always happen, or is it only when the player is still in the marine's body? It would probably be better to implement the xeno queue either way
You might have to ask in the #13-qa channel for specifics on how it works though

**Comment by Dutch-VanDerLinde** [comment]
> Thanks for the PR! 13 deals with this through the xeno queue, which the infected marine and parasite get put to the front of I think Does this always happen, or is it only when the player is still in the marine's body? It would probably be better to implement the xeno queue either way You might have to ask in the #13-qa channel for specifics on how it works though

only when the marine is still in the body

**Comment by Dutch-VanDerLinde** [comment]
and i would add xeno queue if i could, but i can't so i made this instead

**Comment by Sailzington** [comment]
My worry is that this incentivizes Marines to play worse, and not follow orders since you would get a guaranteed ghost role, and there is no downside to being captured anymore

**Comment by Dutch-VanDerLinde** [comment]
> My worry is that this incentivizes Marines to play worse, and not follow orders since you would get a guaranteed ghost role, and there is no downside to being captured anymore

the downside to being captured is that you fucking die, it's how it is in CM13

**Comment by Dutch-VanDerLinde** [comment]
if you wanted to play xeno, you would play roundstart xenos

**Comment by musicmanvr** [comment]
> My worry is that this incentivizes Marines to play worse, and not follow orders since you would get a guaranteed ghost role, and there is no downside to being captured anymore

like others have said, you can't play marine after you die, those are the stakes

**Comment by Sailzington** [comment]
The downside to being captured is that you are round removed and have to wait +40 minutes sometimes. Thats why people listen to command and stay behind cades. Now you can just run to the front, not listen to orders because you want to shoot something, get captured and get a free ghost role guaranteed! This is just rewarding players for the wrong reasons…

**Comment by Rainbeon** [comment]
> if you wanted to play xeno, you would play roundstart xenos

If you're not there at roundstart and want to play Xenos (there are plenty, including me), you would spectate and wait for a larva, with this as a mechanic it would be much faster and more convenient for the player on a personal-level to pick marine and just run in and die. Doing so adds an additional xeno to the opposite team and instead of being punished for deliberately killing yourself (for the latejoining Xeno, missing x amount of Larva rolls), you are rewarded with a guaranteed slot on Xenos and collectively worsened the experience for actual Marine players as you've added +1 to Xeno ranks.

There are many other reasons any given player may want to just side-swap to Xeno as well (examples: avoiding fob duty, avoiding Marine-side Hijack, just getting bored of the round in general, and plenty more). These may not be reasons you would think about using, but different players think different things, and many will tend to do what benefits them personally. Just overall this is mechanically encouraging behavior that is detrimental to the round as a whole.

**Comment by Rainbeon** [comment]
> only when the marine is still in the body

As an additional clarifying question, how does this handle Yellow SSD players? In base SS14 the game can still believe the player to be in-body if they were at the time of SSD (a symptom of this issue is the Morgue constantly beeping for some Yellow SSD players, the solution to the annoyance being to just bodybag them).

I ask this because often Marines will just close the game once captured, still in-body and Yellow SSD, instead of /ghosting, and the potential ramifications of this would be the Larva also being Yellow SSD upon bursting. Yellow SSD larva will stay this way forever, effectively making the Larva dead as far as team numbers are concerned, as there is no player-side solution to this occurring.

**Comment by QuietlyWhisper** [comment]
So if you don't get infected you're just shit out of luck because the infected get priority rather than the first dead?

**Comment by thymol-blue** [comment]
Yes, the infected get priority rather than the oldest dead. If the goal is CM-13 parity, I believe Dutch is correct. I think Verm posted some code in the QA chat about it. Basically the priority is burst marine > facehugger that hugged > queue.

The alternative is TGMC queue whereby it is based on a button click to join the larva queue not death timer. That is, the person who clicked the "join larva queue" button the longest time ago will be 1st. They don't have anything about the burst marine or facehugger.

**Comment by Dutch-VanDerLinde** [comment]
Queue won't really matter though? If the bursted marine is always at the top of the queue, it's basically the exact same

**Comment by deltanedas** [comment]
> people listen to command and stay behind cades.

clearly never played the game this is false :trollface:

getting capped 5m after deploying is nasty at least with this you get to do something

**Comment by Rytil** [comment]
I think its fine if they can queue to be a xeno, but rewarding bad gameplay seems counter intuitive. It would also have people who are essentially feeding the xenos more players because they wanted to be xeno, but couldn't pick it since the round already started (or for some reason they couldn't roll it)

**Comment by deltanedas** [comment]
people who are antag rolling 1. can be bwoinked 2. can already just /ghost roundstart and wait for parasite or larva to open up

**Comment by noisrevni-dev** [comment]
This feature is actually make sense, reminds me those zombie games that if you bitten and got full infection, you become the zombie. Almost no difference in terms of mechanic. People also seems complaining of marines going suicide bomber, this feature will lessen that problem because if you suicide bombing, you pretty much round removed until some empty larva slot open or play as parasite more often.

**Pull request closed without merging**
