### PR TITLE
alternative rouny plushie

### PR DESCRIPTION
**Pull request by noctyrnal**
## About the PR

Adds another rouny inspired by the lizard plushie, designed to be a silly new feature for RMC as how the lizard plushie and weh itself was for SS14.

## Why / Balance

thats a rouny

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes

**Changelog**

:cl:
- add: Added a new rouny plushie. rouny.

### CODE REVIEW

**Comment by Zarq0** [comment]
rouny

**Comment by Kadeo64** [comment]
rouny
plushie_wehny

**Comment by noctyrnal** [comment]
rouny

**Comment by noctyrnal** [comment]
test fail seems to be entirely unrelated to PR, as its present on my shiva port PR and it's due to something with the savanna and not having a component?

**Review by QuietlyWhisper — APPROVED** [review]
thanks

**Pull request merged**
