### PR TITLE
Fix machete scabbard not going on suit slot + more sprites

### LINKED ISSUE #4117: Scabbards should show on belt
## Description

Easy PR, just need to dupe the equipped sprites for the other slots.

**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Title.

## Why / Balance

parity, fixes #4117. You haven't lived until you have at least 2 machete pouches and 3 machete scabbards equipped at once.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Machete scabbards fit in the suitstorage slot

### CODE REVIEW

**Comment by crystalHex** [comment]
To be fair, I did not see mention of the suit storage slot in the scabbard definition:

image

**Comment by Vermidia** [comment]
Yeah, suitstorage items are defined on the armor itself, which can be a lil weird to search out.

**Comment by crystalHex** [comment]
Ah yeah that would explain it

**Review by DrSmugleaf — DISMISSED** [review]
Thanks for the PR!

**Pull request merged**
