### PR TITLE
Disposable Rocket Launcher

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
Introducing the **Rapid Anti Structure / Kinetic Explosive Launcher**, or **RAS/KEL**. _(patent pending)_ 

An Infantry-portable disposable anti-structure launcher. Featuring a limited yield rocket in a cheap tube, allowing you to **THUMP!** and dump. Similar in design to classics such as the M79 LAW and RPG-27

## Why / Balance
It's something new for marines to play around with, as well as opening up new opportunities and strategies, for both Marines to use, and Xenoids to counter. It acts as both a breaching tool against hives and an AT option against heavy xenoids.

The primary drawback is the single use nature, and the difficulty carrying them, as it takes either the suit storage or back slot to carry. If someone was particularly insane they could bring four with them, but it would be their only weapon, barring the potential for a pistol.

## Media

[ PROPAGANDA PHOTOGRAPHY WILL BE PRESENTED SOON]

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

* Add: New disposable rocket launchers for Grunts to play with.

### CODE REVIEW

**Comment by Kadeo64** [comment]
I can't wait to make some xenos E.A.T. it

**Comment by ZA24567** [comment]
super hyped this thing looks awesome

**Comment by JoeHammad1844** [comment]
should make it foldable like the M72 LAW, where you cant fire it if its unfolded and cant be stored anywhere if unfolded

**Comment by KittenColony** [comment]
:)

So this won't be added until the roadmap is complete, as a teaser, you can keep this draft. If you remind me when we start adding new shit then I'll mark it as ready for review, but until then this exists as a jumping point for the SADAR o7

**Comment by KittenColony** [comment]
> should make it foldable like the M72 LAW, where you cant fire it if its unfolded and cant be stored anywhere if unfolded

too OP lmao, that would never be allowed to fly

**Comment by JoeHammad1844** [comment]
> too OP lmao, that would never be allowed to fly

im not saying it should be allowed in bags

**Comment by KittenColony** [comment]
oh, you already do that, you wield it and it unfolds

**Comment by JoeHammad1844** [comment]
nice

**Comment by KittenColony** [comment]
that was NOT the right fucking button

**Comment by DrSmugleaf** [comment]
Reopen this when we get back to it operation 0 PRs open

**Pull request closed without merging**
