### PR TITLE
Corpse Spawners

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

- Adds spawners and loadouts for corpses of Unknown, Prisoner, Chef, Doctor, Engineer, Scientist, Shaft Miner, Security Officer, Prison Guard, Liaison, Colonists
- Also adds Jackboots

## Media

зображення

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Thanks for the PR1
From 13, the shaft miners, scientists and security officers all seem to be chestburst as well, at least on Solaris

**Comment by Tunguso4ka** [comment]
> the shaft miners, scientists and security officers all seem to be chestburst as well

thank you! I forgot about it...

**Review by Vermidia — CHANGES_REQUESTED** [review]
Can you maybe use RandomHumanoidSettings (with a species blacklist, I'm not exactly sure how upstream gets the species pool) to have the species be random too?

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!
Making them different species TBD

**Pull request merged**
