### PR TITLE
Explosions now stun and throw mobs

### PR DESCRIPTION
**Pull request by vero5123**
## About the PR
Title

## Why / Balance
Similar to CM13, explosions should stun mobs in close vicinity, xenos shouldn't be able to dance around nades, same goes for marines. This makes nades a double edged sword where they are now relatively more impactful if used correctly but if you screw up then the ff damage can also be significant. 

## Technical details
We can maybe make this an optional parameter instead, so that some mobs like queen and crusher can potentially be immune to these effects.  

## Media

https://github.com/RMC-14/RMC-14/assets/73014819/80a2da72-ac73-47be-9ed6-d9478063e315

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl:
- add: Explosions will stun & toss mobs in close vicinity

### CODE REVIEW

**Comment by vero5123** [comment]
maybe the overall quantity of nades can be reduced as well, but I mean that probably will happen regardless once more weapons & kit choices are added.

**Comment by JoeHammad1844** [comment]
nothing wrong with lots of nades

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
This should probably be in a configurable component for mobs instead of in the base code, but the effect it self looks great

**Comment by vero5123** [comment]
as discussed in the technical details section I think having a field value for whether or not the mob is affected by the explosion might be a good idea, however, I don't think the actual adjusted force should be a configurable parameter.

**Comment by vero5123** [comment]
I'm going to refactor the nade's effects on mobs entirely.

**Comment by vero5123** [comment]
i'll get back to this later, unless someone beats me to it.

**Pull request closed without merging**
