### PR TITLE
New Distress Signal Map: Solaris Ridge aka Big Red

### LINKED ISSUE #2415: Port Solaris Ridge
- https://cm-ss13.com/w/images/9/9e/Solaris_Ridge.png
- https://webmap.affectedarc07.co.uk/maps/cm/solaris/

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

_Classification: We-Ya Biological Storage Depot_
_Location: LV-1413 (Routerra I)_
_Population: ~120_ 

Solaris Ridge, also known as Big Red. It was the second original map to be added to cmss13 and it will be the second to be added to RMC-14 (if successful merg)

Closes #2415 

## Media

Solaris-0

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Tunguso4ka
- add: Ported Solaris Ridge

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
:'(

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Remove all cable wiring, use always powered lights. don't worry about reporting unpowered devices for now, thanks!

You should be able to remove them / replace them within the yml file

**Comment by Tunguso4ka** [comment]
I dont know why IntegrationTest fail and why the gravity doesnt work..

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
The test error seems to be from the CMDeployableBarriers trying to anchor onto an invalid position. You could try removing them in the map yaml and then mapping them back in if any of them are in an invalid location.

These welders near the top left landing zone need to be random tool spawners.
From CM13, it will spawn one of: Crowbar, screwdriver, welding tool, wirecutters, wrench or flashlight.
image

These fogs near the bottom center on the fences need to be moved to the cave opening.
Once we have C4 and breaching charges we can replace this with the proper doors.
image

Bottom landing zone should be named "LZ2: Engineering Landing Zone" and top landing zone should be named "LZ1: Communications Landing Zone" (even if we don't have comms implemented yet)

This medkit bottom right of top left landing zone needs to be a radiation first aid kit
image

**Comment by Tunguso4ka** [comment]
GREEN CHECKS, WE ARE SO BACK

**Comment by Tunguso4ka** [comment]
Ready to review.

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
There should only be fog walls where checkpoint gates would be normally, you're blocking off areas xenos normally have access to.

the blockers on cm13 map is used to block vehicles.

Need to port the checkpoint gates, they take a long time to acidify or something, don't remember

**Comment by QuietlyWhisper** [comment]
Can you check if xenos have mapped spawns, they're apparently spawning at 0,0 (outside of the map)

**Comment by Tunguso4ka** [comment]
> Can you check if xenos have mapped spawns, they're apparently spawning at 0,0 (outside of the map)

cant replicate
зображення

зображення

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Missing dropship nav on lz2
image

**Comment by QuietlyWhisper** [comment]
Smug will take over the rest, will probably be merged after 24/7 uptime has already started

**Comment by thymol-blue** [comment]
One of the unique things about this map is the inability to spread weeds to certain locations due to the sand @Tunguso4ka 

I am sorry, I haven't had to chance to look at the tiles so I don't know if you did this already but can you add component to the relevant tiles in this or a separate PR? See this commit by Smug for details https://github.com/RMC-14/RMC-14/commit/86870cd7bac96b3231aefa1271c711e7ec3556ba

`- type: BlockWeeds`



This may be dramatic, but if weeds can spread everywhere the xenos will have an enormous advantage.

**Comment by Tunguso4ka** [comment]
> I don't know if you did this already

No, i didnt.

I will fix it tommorow in separate PR.

**Comment by Tunguso4ka** [comment]
> One of the unique things about this map is the inability to spread weeds to certain locations due to the sand

i can find any kind of proof of that. According to the `code/game/turfs/open.dm`  `/turf/open/mars_dirt` seems to be weedable.

**Comment by Tunguso4ka** [comment]
done.

**Comment by Tunguso4ka** [comment]
idk why IntegrationTest fail. Maybe false maybe not.

**Review by DrSmugleaf — APPROVED** [review]
god bless

**Pull request merged**
