### PR TITLE
Change suicide delay to 2 seconds

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
- https://github.com/cmss13-devs/cmss13/pull/7294

:cl:
- tweak: Changed gun suicide do-after delay from 4 to 2 seconds.

### CODE REVIEW

**Comment by MACMAN2003** [comment]
outside the scope of this PR but i feel like a confirmation box would be required before this is merged, primarily because 2 seconds is not a lot of time to cancel the action.

**Comment by deltanedas** [comment]
confirmation box would make it too long to kill yourself to avoid capture, especially if you get tunnel vision

**Comment by crystalHex** [comment]
As long as this remains in the rules (see screenshot) and as long as the keybind for suiciding is the same as a mundane action, e.g. vaulting a window frame, there really should be a confirmation window.

image

**Comment by Dutch-VanDerLinde** [comment]
> As long as this remains in the rules (see screenshot) and as long as the keybind for suiciding is the same as a mundane action, e.g. vaulting a window frame, there really should be a confirmation window.
> 
> image

An admin isnt gonna ban you for accidentally suiciding yourself

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
