### PR TITLE
Nerf Warrior (discussion PR)

### PR DESCRIPTION
**Pull request by Kadeo64**
## About the PR
I've nerfed warrior's melee damage. 
warrior base melee goes from 35 > 20
warrior punch ability goes from 25 > 20
This PR is meant as one of them "discussion PRs" 
## Why / Balance
Warrior is too strong right now. It's actually insane what warriors can do, wiping entire squads since they deal insane damage and virtually cannot die with lifesteal unless an entire squad is focusing them. This PR is meant as a simple fix to make Warriors less devastating, although I doubt this will get merged as other people are making interesting warrior nerf PRs. 
## Technical details
like two lines have been changed in warrior.yml
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Verification31** [comment]
I dont think the problem relies within their damage output, its in their lifesteal. I think cause we have wideswing, it makes it a lot easier for xenos to hit marines, allowing warriors to survive off of their lifesteal more.

**Comment by Kadeo64** [comment]
> I dont think the problem relies within their damage output, its in their lifesteal. I think cause we have wideswing, it makes it a lot easier for xenos to hit marines, allowing warriors to survive off of their lifesteal more.

I do think part of the problem is the lifesteal, but also, warrior being able to survive in groups of people wouldn't be as bad as it is right now if they didn't deal as much damage as they did.

**Comment by QuietlyWhisper** [comment]
Doesn't seem necessary

**Comment by Kadeo64** [comment]
yeah this PR sucks but warrior needs something done, i'll leave that up to the #contributors channel to figure out

**Pull request closed without merging**
