### PR TITLE
Make the 'none' undershirt marking option require male sex

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
title

## Why
evil

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
Brother its 2024

**Comment by foob1** [comment]
> Brother its 2024

16+ server btw
image

**Comment by Tunguso4ka** [comment]
> give me a good reason why people should be able to walk with their titties out upon spawning in

Whats wrong with that? Boobs are not a taboo.

**Comment by foob1** [comment]
> Whats wrong with that? Boobs are not a taboo.

Listen I'm not gonna go into a full on explanation on why having exposed breasts is usually seen as sexual and if you're scratching your head at why this is an issue at all, I think you need to retake your sex ed class but if sexual content existing in a 16+ game is being brushed aside out of the fear that changing it might be viewed as sexist to some, I think that it would be better to just require everyone to have a top and to remove the option to have "none" for both sexes.

**Comment by DrSmugleaf** [comment]
@foob1 What are you on about lol
Go on Lizard right now and spawn in, have you just now started playing SS14
I'm not bothering to argue you why what you are saying is clinically insane, not least because its a sprite in a 2D game, but if for some reason you are compelled to argue this nonsense further then do so on the Discord, not shitting up the GitHub.

Upstream screenshot btw
image

**Comment by DrSmugleaf** [comment]
@foob1 As an addendum, here's SOP saying what you are allowed to wear 5 seconds after you get out of cryo, which I'm surely you are acutely aware of considering how you constantly get into shit for refusing to wear your helmet despite orders to do so

Uniform Regulations
USCM and USCM-affiliated personnel are required to be wearing appropriate clothing during operations. Marines and MPs should be wearing their uniform, boots, and armor at a minimum. Other crew must wear their uniform and assigned footwear, or a standard issue replacement. Headwear, if any is worn, must be your properly assigned headgear, or an acceptable replacement.

**Comment by Carolyn3114** [comment]
we all know boobies are inherently sexual, so sexual, so evil

**Pull request closed without merging**
