### PR TITLE
Move tactical map to the alerts bar

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

moved the tacmap action to the alerts bar
## Why / Balance

the tacmap messed up the order of the actions bar too often so i felt that it'd be better if it was moved to the alerts bar.
## Technical details

i'm going to be completely honest, i don't know how the hell it works. but it does work, i think. i tested it and it worked on my machine.
the (marine side) code works like the squad tracker alert code, as in a headset is needed to be equipped for it to work.
the xeno side just moved it from the actions bar to the alert bar.
## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The tactical map can now be opened from the alerts sidebar instead of only the actions bar.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
Based

**Comment by Dutch-VanDerLinde** [comment]
did you test it for xenos

**Comment by MACMAN2003** [comment]
> did you test it for xenos

yes, the queen can modify it and the regular xenos can't

**Comment by Rainbeon** [comment]
Can these be added to ghosts? Pretty sure it'd be an easy YML change with this system and is needed for #4109

**Comment by MACMAN2003** [comment]
> Can these be added to ghosts? Pretty sure it'd be an easy YML change with this system and is needed for #4109

from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time

**Comment by Vermidia** [comment]
They're supposed to be able to view both separately, not at the same time

**Comment by Dutch-VanDerLinde** [comment]
> > Can these be added to ghosts? Pretty sure it'd be an easy YML change with this system and is needed for #4109
> 
> from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time

For now i'd say just make ghosts access just the marine tacmap for now and someone else can add the xeno map later

**Comment by Rainbeon** [comment]
> from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time. which would require someone significantly smarter than me to figure out.

Ghosts have 3 tacmaps, a live dual-sided one, the marine printout one (the one a Rifleman would have), and the xeno printout one (the one a drone would have)

I am not asking you to make a dual-sided one, just the marine/xeno printouts independently

**Comment by Rainbeon** [comment]
> For now i'd say just make ghosts access just the marine tacmap for now and someone else can add the xeno map later

Is there some unique limitation that'd make the Xeno map not doable? This PR has both already, I'm just asking for the comps on ghosts

**Comment by MACMAN2003** [comment]
> > from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time. which would require someone significantly smarter than me to figure out.
> 
> Ghosts have 3 tacmaps, a live dual-sided one, the marine printout one (the one a Rifleman would have), and the xeno printout one (the one a drone would have)
> 
> I am not asking you to make the dual-sided one, just the marine/xeno printouts independently

this is also beyond my ability

**Comment by Rainbeon** [comment]
> > > from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time. which would require someone significantly smarter than me to figure out.
> > 
> > 
> > Ghosts have 3 tacmaps, a live dual-sided one, the marine printout one (the one a Rifleman would have), and the xeno printout one (the one a drone would have)
> > I am not asking you to make the dual-sided one, just the marine/xeno printouts independently
> 
> this is also beyond my ability

Does adding the GrantTacMapAlert and TacMapXenoAlert components to MobObserver just not work?

**Comment by MACMAN2003** [comment]
> > > > from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time. which would require someone significantly smarter than me to figure out.
> > > 
> > > 
> > > Ghosts have 3 tacmaps, a live dual-sided one, the marine printout one (the one a Rifleman would have), and the xeno printout one (the one a drone would have)
> > > I am not asking you to make the dual-sided one, just the marine/xeno printouts independently
> > 
> > 
> > this is also beyond my ability
> 
> Does adding the GrantTacMapAlert and TacMapXenoAlert components to MobObserver just not work? Running a simple test with other alert types (since I don't have your branch downloaded) seems to be fine
> 
> image

from my understanding of the code, it'd either show both sides at the same time, or neither and crash.

**Comment by Rainbeon** [comment]
> from my understanding of the code, it'd either show both sides at the same time, or neither and crash.

I ended up testing it because I got curious and what actually happened is you can open each one individually a single time (after closing the first one you opened), and then the game just seems to forget that anything was ever drawn there and spits out a blank map, so yeah would need a different PR

**Comment by DrSmugleaf** [comment]
> > Can these be added to ghosts? Pretty sure it'd be an easy YML change with this system and is needed for #4109
> 
> from what i've seen poking through the tacmap code, it'd require an extensive change to the system itself to be able to support showing both xeno and marine tacmaps at the same time. which would require someone significantly smarter than me to figure out.

Making the ghosts able to see both marines and xenos for now is fine, I didn't design it with a separate tacmap in mind for them but I can do that later

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
I'm not sure how I feel about this since it might make it harder for people to find the tac map, we already have new players from time to time ask how to look at it
We could do both the action and alerts bar, and if the player wants just the alerts bar they can right click the action to remove it, I'd be more ok with that

**Comment by MACMAN2003** [comment]
re-added the tacmap to the action bar

**Review by DrSmugleaf — APPROVED** [review]
ty

**Pull request merged**
