### PR TITLE
Crew medical vendor

### LINKED ISSUE #2785: missing doctor vendor
## Description

the vendor that gives doctors their gear doesnt exist

### PR DESCRIPTION
**Pull request by Dorragon**
## About the PR

Adds basic medical equipment vendor for crew medical, inventory corresponds to that of CM13 nurse equipment, i don't think RMC14 has functionality to allow one vendor give different things to different jobs, and splitting it into different vendors would hinder medical preparing for the worth of three adittional items for the doctors (stethoscope, penlight and labcoat)

closes #2785 
## Why / Balance

No more nurses/doctors joining only to see that there are no medhuds and medical belts left
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Medical crew vendor

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
medical kit pouch exists, you dont need to comment it out

**Comment by JoeHammad1844** [comment]
probably

**Comment by Tunguso4ka** [comment]
Add `Closes #2785` please.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
