### PR TITLE
Fix chemistry chem metabolisms + parity hunger

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Changed all the basic chems metabolisms to match their effects and colors on CM, if they had any, and removed any upstream fluff that wasn't nessary.

Also changed humanoids to use hunger values from CM, and modified nutriment to match CM in how much it gives.

## Why / Balance

Parity.

## Technical details

The most suspect is the nutrition drain of iron. I saw that the code scales satiate with metabolism rate, so not only is it scaled with our max hunger, it's also x10 to match the metabolism rate. Testing in CM the conversion matches for blood and nutrition.

All damage rates are 1/2 like the medicines so they can process over 0.1 secs correctly.

## Media

color
(Note iron and lithium fixed later, got their colors confused with their fire colors)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Fixed metabolism rate and properties of basic dispenser chems. Most dispenser chems are shown as unknown on the health analyzer.
- fix: Iron correctly heals more blood but also requires nutrition and drains it as it processes.
- fix: Nutriment heals blood if you're not hungry
- fix: Modified Prepared MRES and components to intended values

### CODE REVIEW

**Comment by Vermidia** [comment]
I think I need to look at the conversion rate more, doesn't match up with the medicines right

**Comment by Vermidia** [comment]
Confirmed the values seem to be correct for damage blood etc.

**Comment by Vermidia** [comment]
Actually, going to try unscaling the hunger stuff and just, changing our nutrition stuff to match CM.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
