### PR TITLE
Feat/extended-gamemode

### PR DESCRIPTION
**Pull request by 0xRainy**
## About the PR

Added Extended gamemode

I'm opening this as a draft because I have no idea if the way I've done this is the right way

## Why / Balance

I'm tired of entering commands to stop the round ending when testing 😮‍💨
## Technical details

I basically copied the DistressSignal mode and ripped out some parts of it to make the round last until both xenos and marines are all dead.

I'm not sure if all of the code I left in is needed or if some of the code I removed is actually necessary for certain situations in a round.

I've tested it as well as I can with 1 player on the server

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Extended gamemode

### CODE REVIEW

**Comment by Kadeo64** [comment]
you know what would be really fun? if extended allowed xenos and marines to talk to eachother. I don't know if that's directly possible though

**Comment by 0xRainy** [comment]
> you know what would be really fun? if extended allowed xenos and marines to talk to eachother. I don't know if that's directly possible though

Could probably do this with a new component like `UniversalTranslator` and a small change to https://github.com/RMC-14/RMC-14/blob/dfb5a1654290fc72aa1a916cf2b554908dfa5cc1/Content.Server/_RMC14/Chat/Chat/CMChatSystem.cs#L36-L37
https://github.com/RMC-14/RMC-14/blob/dfb5a1654290fc72aa1a916cf2b554908dfa5cc1/Content.Server/_RMC14/Chat/Chat/CMChatSystem.cs#L55-L56

then add the component when they spawn, might work.. there may be a better way of doing it though

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Thanks for the PR!
Need to go through and de-duplicate this code because just copy pasting the bits of distress signal without the end-game round part isn't ideal
Could have a boolean on the game rule for whether or not to check for round end conditions instead

**Comment by 0xRainy** [comment]
> Thanks for the PR! Need to go through and de-duplicate this code because just copy pasting the bits of distress signal without the end-game round part isn't ideal Could have a boolean on the game rule for whether or not to check for round end conditions instead

Some real life stuff came up but I will work on it this week, thanks for the feedback

**Comment by 0xRainy** [comment]
Gonna close this, I havent been able to figure it out.

**Pull request closed without merging**
