### PR TITLE
Scabbards

### LINKED ISSUE #659: L44 M37A2 Scabbard

### LINKED ISSUE #660: H5 Pattern M2132 Machete Scabbard

### LINKED ISSUE #1341: 5 Machete Scabbard (Full)

### LINKED ISSUE #1365: 0P Shotgun Scabbard

### LINKED ISSUE #1414: 15P Machete Scabbard (Full)

### LINKED ISSUE #1450: 4P Machete Scabbard (Full)

### LINKED ISSUE #1515: Machete Scabbard (Full)

### LINKED ISSUE #1601: Machete Scabbard (Full)

### LINKED ISSUE #1660: 6P Machete Scabbard (Full)

### LINKED ISSUE #1686: Machete Scabbard (Full)

### LINKED ISSUE #1774: 6P Machete Scabbard (Full)

### LINKED ISSUE #1852: 6P Machete Scabbard (Full)

### LINKED ISSUE #1917: 5P Machete Scabbard (Full)

### LINKED ISSUE #2269: 5 Shotgun Scabbard

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

Ported the following scabbards:
- H5 pattern M2132 machete scabbard
- ML66A harness machete scabbard
- M42A2 shotgun scabbard

## Why / Balance

CM13 parity
Resolves #659, resolves #660, resolves #1341, resolves #1365, resolves #1414, resolves #1450, resolves #1515, resolves #1601, resolves #1660, resolves #1686, resolves #1774, resolves #1852, resolves #1917, resolves #2269

## Technical details

Ported textures from CM13
YAML for prototypes
C#: a new component to ignore the SG backpack restriction (for the SG machete scabbard) plus appropriate checks

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added two new machete scabbards (one for the smart gun operator) and a shotgun scabbard.

### CODE REVIEW

**Comment by crystalHex** [comment]
Screenshot of empty and filled scabbards:
image

**Comment by crystalHex** [comment]
Quick demo:

https://github.com/user-attachments/assets/fbb5d8fb-b0ff-4ff8-942a-f2b72abc88a4

**Comment by crystalHex** [comment]
Still to do: get the worn scabbards to display whether they're empty or not
I'll get that fixed in a separate PR, once all the holsters/scabbards get merged, so I can do them all at once

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
