### PR TITLE
Undershirts and Underwear

### LINKED ISSUE #3486: Marines should spawn in underwear rather than full uniform from hypersleep
CM13 parity

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

- Ports 5 undershirt variants and 3 bra variant
- Ports 5 underwear variant

Default underwear is boxers.

closes #3486

## Media

зображення

зображення

зображення

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added undershirts and underwear markings, check your Marking customization menu!

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
is it forced? Cuz it should

**Comment by Dutch-VanDerLinde** [comment]
and marines should spawn with no uniform, just in their underwear

**Comment by Tunguso4ka** [comment]
> is it forced? Cuz it should

underwear yes. undershirt no.

**Comment by Tunguso4ka** [comment]
> and marines should spawn with no uniform, just in their underwear

yeah, i done that. (Check files)

**Review by DrSmugleaf — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
