### PR TITLE
Varadero assets v2

### PR DESCRIPTION
**Pull request by Aurallianz**
## About the PR
Added components for New Varadero mapping. 
Added new Varadero.

Needs:
APCs.
Light fixtures.
Areas.
Semiotics.
Door Permissions
Survivor Mapping
_**Mapping REVIEW!!!**_

## Why / Balance
**_PARITY BABY!!!_**

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Added New Varadero
Added New Varadero mapping components.

:cl:
- add: New Varadero.

### CODE REVIEW

**Comment by Kadeo64** [comment]
rmc14 beach episode real

**Comment by Aurallianz** [comment]
Funny YAML Linter Issues: I have to remove the suffixes from tiles (Upstream issue)
As for the test debug, I think I forgot to remove the collisions from the plants when I removed the physics, although I kind of have no clue how to fix this, lol.

**Comment by DrSmugleaf** [comment]
```
System.Collections.Generic.KeyNotFoundException : The given key 'RMCWood' was not present in the dictionary.
```

```
  1) Prototype BonsaiTree02 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  2) Prototype StalkyBush03 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  3) Prototype FernyBush03 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  4) Prototype FernyBush02 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  5) Prototype FernyBush01 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  6) Prototype BonsaiTree01 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  7) Prototype StalkyBush02 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  8) Prototype BonsaiTree04 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  9) Prototype StalkyBush01 modifies component on spawn: Physics. Modified yaml:
canCollide: False
...

  10) Prototype BonsaiTree03 modifies component on spawn: Physics. Modified yaml:
canCollide: False
```

**Comment by Aurallianz** [comment]
I'm assuming that the build test is failing because of the Orion cat spawner; I'm assuming we can ignore that?

**Comment by Aurallianz** [comment]
It occurred to me that i should note this is still a grid and not a map.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
