### PR TITLE
Fix/Xeno can no longer interact or open UI for a lot of things

### LINKED ISSUE #2435: You should not be able to open storages as a xeno

### LINKED ISSUE #2740: Xenos can open / close lockers, allowing them to hide marine bodies

### LINKED ISSUE #2909: Xenos can toggle IVs (and possibly other right-click human interactions)
## Description

Xenos can right-click-dropdown interact with certain human things. I noticed this with blood IVs but haven't tested any other items.

**Reproduction**

- Right-click an IV as a xeno
- Click the Toggle button (in the right-click popup)
- The IV will now draw blood rather than inject it

**Screenshots**

image

**Additional thoughts**

Is this really a problem? Dunno, lurkers sabotaging IVs could be funny. I do assume this may cause problems with future items however. Xenos aren't supposed to touch human things.

### LINKED ISSUE #3087: Xenos can remove items from Cryosleeping players
## Description
Xenos can strip items from Cryosleeping players in Cryogenic Sleep Units. Fairly minor bug (or atleast, I can not currently think of any large usecases at this time) but Xenos should not know how to use machines like this.

**Reproduction**
1. Have a marine/non-xeno use Cryosleep
2. Xeno clicks on Cryogenic Sleep Unit
3. Xeno can now remove any of their items, these are dropped on the floor upon removal.

**Screenshots**
https://github.com/user-attachments/assets/873ecf86-7437-4be8-92c9-7aeb48773663

### LINKED ISSUE #3148: Xenos can spill chems / change transpher amount on chems
Title

### LINKED ISSUE #3193: Xenos can deflate inflatable walls / door
Title

### PR DESCRIPTION
**Pull request by 0xRainy**
## About the PR

Partially fix #3193 
Fixes #3148 
Fixes #2909 
Fixes #2740 
Fixes #2435 
Should also fix #3087 but I think cryostorage UI is broken? I can't reproduce even with a non-xeno, UI always shows the cryostorage is empty

Xenos can no longer interact with:
	Chem Dispenser
	Chem Master
	Buckets
	Jugs
	Beakers
	Bottles
	Bodybags/Stasisbags
	Portable Heaters
	Crates
	Armor
	Backpacks
	Satchles
	Webbing
	Belts
	Pouches
	Packets (Grenades, Pills, etc)
	Gun Cases
	Ammo Boxes
	Boxes
	Cigarettes/Cigars
	Mini packet of cigs
	Flasks
	Marine Radiophone
	First Aid Kits
	Morgue
	Crematorium
	Matchbooks
	Soda Fountain
	Bodbda
	Lamps/Flashlights
	Rollerbeds
	IV Drips
        Bloodpacks
	Vending Machines
	Hypersleep Chambers
	Microwaves
        Hydroponics Trays
	Requisitions Computer
	Inflatable Walls
	Disposal Units
	APC
	Lockers
	Fax Machines
	Filing Cabinets
	Paper Bins
	Clipboards
	Folders
	Intercoms
Inflatable doors are still interactable, and disassembalable because otherwise xeno wouldn't be able to pry them

## Why / Balance

Well they shouldn't

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Screenshot_20240722_232513

## Breaking changes

I tried my best to keep the additions to _RMC14 yml files only but some things had to go in SS14 yml files

**Changelog**

:cl:
- fix: Xenos can no longer interact with a LOT of items

### CODE REVIEW

**Comment by deltanedas** [comment]
would it not make more sense to have this be a whitelist for the xenos

**Comment by Dutch-VanDerLinde** [comment]
just make a whitelist for the xenos, the blacklist causes conflicts because you're editing upstream files

**Comment by 0xRainy** [comment]
> just make a whitelist for the xenos, the blacklist causes conflicts because you're editing upstream files

I've moved everything to RMC prototypes except for the portable heater which we don't have a version of (I'm fine not including it, I did initially because it appears on a map). 

The reason I'm using a blacklist is because that is the system that was implimented and I don't think a whitelist would be a meaningfully shorter list. There are a lot of things a xeno should be allowed to interact with like marines, other xenos, structures like cades (rattling them), doors, etc. I also would rather allow than restrict by default.

**Review by DrSmugleaf — DISMISSED** [review]
Thanks for the PR!

**Pull request merged**
