### PR TITLE
Update Solaris: NavPoints, Faxes, Cades

### LINKED ISSUE #2987: Solaris dropships land one tile further back than they should
## Description
the dropships for at least LZ1 are not landing entirely on the landing pad

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

Basically title.

- There should be no sandbag cades on Solaris, i added them previosly only because we didnt have wooden cades.
- Removed double vender.
- Named faxes
- Added NavMap points
- Fixes #2987

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
the map error is back help

**Comment by Tunguso4ka** [comment]
> the map error is back help

me fix.

**Comment by Tunguso4ka** [comment]
me not

**Comment by Tunguso4ka** [comment]
i somehow break pip update.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
