### PR TITLE
Add Medical, Req access to Secure Surgery Crate. Add Corp, Req access to Weya Crate

### LINKED ISSUE #3065: The CMO does not have access to the surgery crate

### PR DESCRIPTION
**Pull request by Derrek-Larson**
## About the PR

Resolves #3065 
Add CMAccessRequisitions, CMAccessCorp to WeYa secure crate.
Add CMAccessRequisitions, CMAccessMedical to Surgery secure crate.
## Why / Balance

Secure Crates should be secure.
Medical/req should have access to surgery crate.
Corp/req should have access to weya crate.
## Technical details

Make secure surgery and secure weya crates secure by adding access requirement for lock/open in crates.yaml
## Media

https://github.com/user-attachments/assets/f6cd1fcb-0a50-42f0-a53f-76b468b883c2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

YAML Changes:
crates.yaml
add type AccessReader to CMCrateSecureSurgery
access CMAccessRequisitions, CMAccessMedical
add type AccessReader to Weya Secure Crate
access CMAccessRequisitions, CMAccessCorp
**Changelog**

:cl:
- add: Medical access, Requisition access to Secure Surgery Crate
- add: Corporate access, Requisition access to WeYa Secure Crate

### CODE REVIEW

**Comment by Derrek-Larson** [comment]
Created to address
https://github.com/RMC-14/RMC-14/issues/3065

**Comment by Tunguso4ka** [comment]
> Created to address

Add `Resolves #issue_number` in your main comment. Github will auto-link issue.

**Comment by Derrek-Larson** [comment]
> > Created to address
> 
> Add `Resolves #issue_number` in your main comment. Github will auto-link issue.

Thanks, Done.

**Comment by TheDoctor1977** [comment]
Req probably shouldn't be able to open secure We-Ya crates, there could be important or confidential (or potentially illegal depending on how cool the admins are that day) material in there that shouldn't be accessed without the Liaison's direct permission.

**Comment by Derrek-Larson** [comment]
> Req probably shouldn't be able to open secure We-Ya crates, there could be important or confidential (or potentially illegal depending on how cool the admins are that day) material in there that shouldn't be accessed without the Liaison's direct permission.

I had considered that, though I figured it'd be best to give them access and remove later if needed. If this needs doing I can remove it and push. Thank you for the feedback.

**Review by QuietlyWhisper — APPROVED** [review]

**Pull request merged**
