### PR TITLE
Port Distress Signal map: Trijent Dam

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

- Adds new map: Trijent Dam.
- Adds new windows for Trijent Dam.
- Adds new road decals.

## Media

FIle too big, so no image.
https://tunguso4ka.github.io/map-viewer/?map=Trijent

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Ported new Distress Signal map: Trijent Dam.

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
needs areas, and will be good to merge.

**Comment by Kadeo64** [comment]
oh no

**Comment by DrSmugleaf** [comment]
I'll look at merging this for the next next update together with power so the filtration machines can function

**Review by DrSmugleaf — APPROVED** [review]
ty boss

**Pull request merged**
