### PR TITLE
Remove all red crosses

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Greenified all the red crosses that I could find.
## Why / Balance

Because the ICRC is a bunch of haters.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

I don't think players should be concerned about compliance with the geneva conventions

### CODE REVIEW

**Comment by Kadeo64** [comment]
why is geneva filled with fun killers? first the geneva conventions, then the red cross.

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Looks good, just two first aid sprites not needed

**Comment by JoeHammad1844** [comment]
does anything actually happen if we keep the red crosses? CM13 has had them for YEARS and NOTHING seems to have happened

**Comment by JoeHammad1844** [comment]
also the white cross with the red background doesnt count as a red cross, since the cross is white

**Comment by MACMAN2003** [comment]
better to be safe and green than red and smited by the killjoys at the ICRC

**Review by QuietlyWhisper — APPROVED** [review]
Thanks!

**Pull request merged**
