### PR TITLE
dont let xenos hug marines

### LINKED ISSUE #3436: RMC14: The wholesome update
Xenos can hug humans

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
they shrimply cant

## Why / Balance
fixes #3436

## Technical details
added `UserBlacklist`

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- fix: Fixed Xenos being able to hug marines, that's what parasites are for.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
MAKE It say caress instead of hug lik e cm13

**Comment by deltanedas** [comment]
nothing in the cm-ss13 repo mentions that caress text idk

**Comment by Dutch-VanDerLinde** [comment]
> nothing in the cm-ss13 repo mentions that caress text idk

Fourty seven
image

**Comment by deltanedas** [comment]
specifically *that* text not this random one, and thats for ovi only

**Comment by Dutch-VanDerLinde** [comment]
> specifically _that_ text not this random one, and thats for ovi only

not this one 
image

**Comment by Dutch-VanDerLinde** [comment]
#1264

**Comment by deltanedas** [comment]
modules/mob/living/carbon/xenomorph/XenoAttacks.dm has the poking bit

**Comment by deltanedas** [comment]
forgor

**Pull request closed without merging**
