### PR TITLE
Make the humanoid bullet hitbox slightly smaller

### PR DESCRIPTION
**Pull request by DrSmugleaf**
## About the PR

To be revisited with hostile factions maybe, but this basically makes it harder to shoot someone behind you too, see screenshot for the longest distance where that happens
Alternative was make guns shoot further in front of you, but that then affects combat vs melee units too

## Media

Content Client_U9RhWrSiX0

Bigger circle is normal collision, smaller circle is bullet collision
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Made the humanoid bullet hitbox slightly smaller (0.35 > 0.25), making humanoids slightly harder to hit with bullets, specially when one is far behind you. You will still shoot someone if they are too close behind you, to prevent stacking. This change doesn't affect xenonid projectiles.

### CODE REVIEW

**Comment by Kadeo64** [comment]
anti-ff PR real

**Comment by Rainbeon** [comment]
Does this affect Spitters and Sentinels as well?

**Comment by DrSmugleaf** [comment]
> Does this affect Spitters and Sentinels as well?

In retrospect it does, need to think about what to do about that because I think they are treated like regular projectiles in 13 too
At worst we could make xeno projectiles collision different

**Comment by Kadeo64** [comment]
> At worst we could make xeno projectiles collision use different groups

that seems like the most obvious thing to do unless you want the spit projectile's hitbox to be larger (and thus get clipped on geometry more often) although idk if that will affect performance at all

**Pull request merged**
