### PR TITLE
Make Queen's screech unable to penetrate walls

### PR DESCRIPTION
**Pull request by Mattshark89**
## About the PR

Queen's screech no longer affects marines behind solid walls such as thick resin. It still affects marines behind non-blocking walls like barricades (think walls that don't prohibit you from, say, grabbing an item on the other side of)

## Why / Balance

For parity with CM13.

## Technical details

The screech's stun and paralyze both check for `InRangeObstructed` between the queen and each marine using a `CollisionGroup.Opaque` mask.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Ignore the shorter screech cooldown, that was done for demo purposes only. EDIT: the screech now works through transparent walls such as membranes and glass; this demo is outdated.

https://github.com/RMC-14/RMC-14/assets/32344718/6a72da9c-78a1-42c3-bbdf-1ee347595493

Also see https://github.com/RMC-14/RMC-14/pull/2856 for discussion around it.

## Breaking changes

**Changelog**

:cl:
- tweak: The Queen's screech no longer affects marines behind opaque walls. It still affects marines behind barricades.

### CODE REVIEW

**Comment by Mattshark89** [comment]
(Ignore the first three commits, they're leftover from my first PR. https://github.com/RMC-14/RMC-14/pull/2856)

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
So I just checked this in 13 and APPARENTLY the Queen's screech goes through resin membrane and other windows. So it should be an Opaque check on the InRangeUnobstructed.

https://github.com/RMC-14/RMC-14/assets/10968691/b4c6f85e-37e1-4ee0-890e-65e3d9f8cd74

**Comment by Mattshark89** [comment]
> So it should be an Opaque check on the InRangeUnobstructed.

Doing this check seems to work better. It works as expected, with one minor quirk I feel may be an SS14 problem. Glass airlocks fit the "Opaque" description when closed, even though they're never given the flag?

https://github.com/RMC-14/RMC-14/assets/32344718/c731ad62-5356-4068-bca2-41bbe98f4278

I assume that's unintended. I'll experiment to see if perhaps I just implemented Opaque-checking wrong.

## -----(More advanced stuff, may help with debugging)-----

See commit https://github.com/RMC-14/RMC-14/pull/2866/commits/5f57f3f05384f728acf5ad3b42c10f7efe4df87e and file https://github.com/RMC-14/RMC-14/blob/master/Content.Shared/Physics/CollisionGroup.cs . The glass airlock's `CollisionMask` is set to 158, a number not containing the bit `1` for opaque, meaning the screech should be passing through.

image

**Comment by Mattshark89** [comment]
### Update on the glass door issue

It's only certain doors. Here's a video showing the ones that work as expected and those that don't (that I found).


https://github.com/RMC-14/RMC-14/assets/32344718/2d9b66a0-feda-4740-94b7-acc1508e5854

It seems to me that the Alamayer doors have perhaps been given the wrong `CollisionLayer` value?

Glass airlock (top one): works

image

door (Medical, glass) (left one) and similar: blocks

image

**Comment by Mattshark89** [comment]
So basically, I believe this PR is ready for review. There's just a door quirk that maybe should be looked at.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
