### PR TITLE
Give FTLs insulated gloves

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Title.

## Why / Balance

CM-13 parity, they get insulated gloves. Yeah, same as CombatTech.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: FTLs get insulated gloves as part of their kit

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
thats not the FTL gear thats the corpsman gear

**Comment by Vermidia** [comment]
dangit

**Comment by Dutch-VanDerLinde** [comment]
Silly goose

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
