### PR TITLE
Smokables update

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR

Changes Cigarette Machine catalog. Ports 3 cm13 cigarette packs. Ports zippo. Corrects matchbook visuals. Tarbacks tarbacks tarbacks. Organizes smokables. Ports matchbox. Ports cigar case. Tarback cigars tarback cigars tarback cigars.
## Why / Balance

Inspired after smoking chunghwa
## Media

https://github.com/user-attachments/assets/3299cd54-f06b-40de-8c38-f3639cb05825

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by MACMAN2003** [comment]
[500 cigarettes.](https://www.youtube.com/watch?v=8liPBsUtND4)

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Thanks for the PR!
The ones with golden W's or other references to copyrighted material need to have those references removed

**Comment by Hyenh** [comment]
> Thanks for the PR! The ones with golden W's or other references to copyrighted material need to have those references removed

Question, just saying We-Ya is fine, right?

**Comment by FungiFellow** [comment]
> Question, just saying We-Ya is fine, right?

Yes

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
New entity IDs should be RMC and not CM

**Review by QuietlyWhisper — APPROVED** [review]
500 cigarettes

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
