### PR TITLE
Custom Built Shotgun

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

Added the Custom Built Shotgun, a 6 round semi auto shotgun that has a 2 round burst

Has Mapped in Planetary spawns alongside being PMC/CLF/Freelancer kit, this PR does not map it in anywhere.

## Why / Balance

Parity
Issue: #3304 
## Technical details

.yml and addition of sprites
## Media

image
image
image
image
image
Fire rate has been adjusted to 0.85

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added the Custom Built Shotgun, a 6 round semi auto shotgun that has a 2 round burst (Surv/PMC Weapon)

### CODE REVIEW

**Comment by mmails** [comment]
Wouldn't this require the black market to be added, for it to be ordered? I'm 90% sure it's a BM item

**Comment by FungiFellow** [comment]
> Wouldn't this require the black market to be added, for it to be ordered? I'm 90% sure it's a BM item

Has Mapped in Planetary spawns alongside being PMC/CLF/Freelancer kit

**Comment by mmails** [comment]
> > Wouldn't this require the black market to be added, for it to be ordered? I'm 90% sure it's a BM item
> 
> Has Mapped in Planetary spawns alongside being PMC/CLF/Freelancer kit

Well that's why i said i was 90% sure :godo:

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
