### PR TITLE
Add camouflage to Marine weapons, armor, and equipment

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Added a metric shit ton of camouflaged variants of existing items. Alongside a system to swap between them on a per selected planetmap basis
## Why / Balance

Parity, alongside 4 times as much tacticool drip.
## Technical details

Added a camouflage field to the thing responsible for handling planet-maps
Added a component and system for swapping out entities with their camouflaged variants when they spawn.
when an entity with the component is spawned, it will add itself to a queue, which is attempted to be processed every tick.
the entity is not replaced on the same tick it is spawned on due to needing the presence of other components.
## Media

image
image

yt link to a barebones video example: https://www.youtube.com/watch?v=j2HC9YZa6r0

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added camouflaged variants of marine weapons, armor, and equipment.

### CODE REVIEW

**Comment by MACMAN2003** [comment]
there is significantly more RSIs than just what the bot commented with

**Comment by Kadeo64** [comment]
good lord

**Comment by Dutch-VanDerLinde** [comment]
It's peak

**Comment by Kadeo64** [comment]
what if patreons could choose which camouflage their equipment used?

**Comment by MACMAN2003** [comment]
yaml linter (and subsequent build & test debug) fail is related but for the life of me i cannot figure out why it's failing

**Comment by CyberTropic** [comment]
image
That's wild, I can't believe someone went in and recoloured all the backpacks at some point

**Comment by Timemaster99** [comment]
> yaml linter (and subsequent build & test debug) fail is related but for the life of me i cannot figure out why it's failing

```
[ERRO] go.comp.sprite: Unable to load RSI '/Textures/_RMC14/Objects/Clothing/Uniforms/MP/warden/tan.rsi'
[ERRO] go.comp.sprite: Unable to load RSI '/Textures/_RMC14/Objects/Clothing/Uniforms/MP/warden/navy.rsi'.
```
These two RSIs aren't reading. Yaml linter fails by default if build fails.

**Comment by MACMAN2003** [comment]
> > yaml linter (and subsequent build & test debug) fail is related but for the life of me i cannot figure out why it's failing
> 
> ```
> [ERRO] go.comp.sprite: Unable to load RSI '/Textures/_RMC14/Objects/Clothing/Uniforms/MP/warden/tan.rsi'
> [ERRO] go.comp.sprite: Unable to load RSI '/Textures/_RMC14/Objects/Clothing/Uniforms/MP/warden/navy.rsi'.
> ```
> 
> These two RSIs aren't reading. Yaml linter fails by default if build fails.

i've checked the two RSIs and they should by all means be loading.

**Comment by DrSmugleaf** [comment]
> i've checked the two RSIs and they should by all means be loading.

It's the change in casing I think, changing the casing of an existing folder doesn't get pushed properly half the time, if you capitalize Warden again it should work

**Comment by Timemaster99** [comment]
> > i've checked the two RSIs and they should by all means be loading.
> 
> It's the change in casing I think, changing the casing of an existing folder doesn't get pushed properly half the time, if you capitalize Warden again it should work

I tested the build and YAML linter locally and found no issue. I've also discovered this same heisentest occurring on #5007 which produces the same errors, but for an RMC purple closet that isn't touched by the PR. 
The logs give `[DEBG] res.preload: Skipping texture preloading due to CVar value.` before the RSI error, which _may_ be what causes it. Either way, it appears the fail is unrelated.

**Comment by Dutch-VanDerLinde** [comment]
``Unable to load RSI '/Textures/_RMC14/Objects/Clothing/Uniforms/MP/Warden/urban.rsi'``

**Comment by Timemaster99** [comment]
> `Unable to load RSI '/Textures/_RMC14/Objects/Clothing/Uniforms/MP/Warden/urban.rsi'`

See discussion above

**Comment by DrSmugleaf** [comment]
This should be setting an appearance value and generic visualizer to change the sprite path instead of deleting and spawning new entities unless there's differences other than the look
I can't add a review to the files because GitHub gives up trying but I can make the change and push them to the PR

**Comment by MACMAN2003** [comment]
> This should be setting an appearance value and generic visualizer to change the sprite path instead of deleting and spawning new entities unless there's differences other than the look I can't add a review to the files because GitHub gives up trying but I can make the change and push them to the PR

that's how I initially intended to implement this but I couldn't for the life of me figure out how (and still kinda can't wrap my head around it), which lead to the brute force method of deleting and spawning a new entity

**Comment by Dutch-VanDerLinde** [comment]
> > This should be setting an appearance value and generic visualizer to change the sprite path instead of deleting and spawning new entities unless there's differences other than the look I can't add a review to the files because GitHub gives up trying but I can make the change and push them to the PR
> 
> 
> 
> that's how I initially intended to implement this but I couldn't for the life of me figure out how (and still kinda can't wrap my head around it), which lead to the brute force method of deleting and spawning a new entity

If ur still having trouble with the appearance data thing I can help you

**Comment by MACMAN2003** [comment]
> If ur still having trouble with the appearance data thing I can help you

yes please

**Pull request merged**
