### PR TITLE
Make knives do extra melee damage against xenos

### LINKED ISSUE #3616: Melee weapons needs to do 1.5x damage against xenos
## Description

**Reproduction**

It sure exists.
52.5 damage to a drone a machete does, so 1.5x it's normal damage.

Using it on yourself or other humanoids just does 35 damage (ignoring armor) but armor isn't ignored for xenos, since crusher takes less damage from it.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
CM13 parity
fixes #3616

## Media

https://github.com/user-attachments/assets/c2f26a30-82ec-45c1-a630-14eaff17d581

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Melee weapons now do x1.5 extra damage against xenonids.

### CODE REVIEW

**Comment by Vermidia** [comment]
Does this also do on thrown hit? Because throwing knives also do extra damage if thrown.

**Comment by Dutch-VanDerLinde** [comment]
No

**Comment by Dutch-VanDerLinde** [comment]
added media

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Thanks for the PR!
This will double-dip on devoured damage I think
The damage for that is already correct, so it might be easiest to lower devour damage to make it the same with this change

**Comment by Dutch-VanDerLinde** [comment]
Lowered devour damage by 0.5% to match the correct values
doesnt lower throwing knife though because the devour damage is so low its basically useless

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
