### PR TITLE
Add new welder sprites + multitool sprite

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Title. I didn't want to cut out the flame + light from the welding tool bit so I just, didn't. I think it's probably fine. Fix is hand welder doesn't need eye protection now.

Thought about doing the no eye damage for hand welders, but they're only supposed to weld vents and doors (and doors take longer) so...yeah not right now.

## Why / Balance

CM parity. I also fixed the medical hud's delays and meta just being uh, wrong.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
coolguy

## Breaking changes

**Changelog**

no cl just sprite

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
does this add the new sounds too

**Comment by Vermidia** [comment]
they got new sounds?

**Comment by Dutch-VanDerLinde** [comment]
activate a welder in cm13

**Comment by Vermidia** [comment]
I seee. I'll try to get it in.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
