### PR TITLE
Make xenonid phermones use radial menu

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
see: #2118

CM13 parity

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: The xeno pheromones menu is now a radial menu rather than a window

### CODE REVIEW

**Comment by lzk228** [comment]
would be good to also add little descriptions to every type of pheromone

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
This needs the help icon from 13 and to be in the same order
image

This is what the help icon prints to chat:
```
Pheromones provide a buff to all Xenos in range at the cost of some stored plasma every second, as follows:
Frenzy (Red) - Increased run speed, damage and chance to knock off headhunter masks.
Warding (Green) - While in critical state, increased maximum negative health and slower off weed bleedout.
Recovery (Blue) - Increased plasma and health regeneration.
```

**Comment by Dutch-VanDerLinde** [comment]
image
image

was able to get the help button done but i'm not sure on how to change the order of the buttons

**Comment by DrSmugleaf** [comment]
> was able to get the help button done but i'm not sure on how to change the order of the buttons

That should depend on what order the buttons are added to parent in the code, you might need to manually set the order of xeno pheromones instead of iterating the enum values

**Comment by Dutch-VanDerLinde** [comment]
@DrSmugleaf 
image
Got the radial buttons to appear in the correct order

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
