### PR TITLE
New Distress Signal Map: Shivas Snowball

### LINKED ISSUE #2414: Port Shivas Snowball
- https://cm-ss13.com/w/images/1/18/Map_icecolony.png
- https://webmap.affectedarc07.co.uk/maps/cm/shivas/

### PR DESCRIPTION
**Pull request by noctyrnal**
## About the PR

A map from CM13 with cold temperatures requiring a coif, and a large ice colony.

Closes #2414 

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

No SS yet because I cant get a render of it working :(

## Breaking changes

**Changelog**

:cl: noctyrnal
- add: Ported Shiva's Snowball

### CODE REVIEW

**Comment by noctyrnal** [comment]
Marked as Draft until I can fix the atmosphere to be cold and the lack of gravity.

**Comment by noctyrnal** [comment]
Now ready for review, though shivas snowball isn't going to be cold until we can figure out how to change a grid's temp.

**Comment by noctyrnal** [comment]
Map should be fixed now, everything is parented to 1 and 2 was erased,

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Thanks for the PR! Shiva real

The diff is too large to point at specific lines for review but:
This needs to be CMSpawnMobMonkey, you should be able to find it in-game with `entities prototyped SpawnMobMonkey visualize` and replace it with the RMC-14 one.
```yml
- proto: SpawnMobMonkey
  entities:
  - uid: 13778
    components:
    - type: Transform
      pos: 200.5,105.5
      parent: 1
```

The two landing zones are missing their spaceborne gauss turrets. These will some day be deployed automatically by the dropship, but for now we just place one in each corner of the LZ, and usually one on each side to make sure it covers the full length of it, plus a couple more to catch any dead spots on the LZ (until we implement gas)

**Comment by noctyrnal** [comment]
> Thanks for the PR! Shiva real
> 
> The diff is too large to point at specific lines for review but: This needs to be CMSpawnMobMonkey, you should be able to find it in-game with the command `entities prototyped SpawnMobMonkey visualize` and replace it with the RMC-14 one.
> 
> ```yaml
> - proto: SpawnMobMonkey
>   entities:
>   - uid: 13778
>     components:
>     - type: Transform
>       pos: 200.5,105.5
>       parent: 1
> ```
> 
> The two landing zones are missing their spaceborne gauss turrets. These will some day be deployed automatically by the dropship, but for now we just place one in each corner of the LZ, and usually one on each side to make sure it covers the full length of it, plus a couple more to catch any dead spots on the LZ (until we implement gas)

Fixed the odd spawner prototype and added the turrets! Shiva real

**Comment by noctyrnal** [comment]
Test is DebugAssertException , no clue how to fix.

**Review by DrSmugleaf — APPROVED** [review]
shivas real ty boss

**Pull request merged**
