### PR TITLE
change xeno melee arc from bite to claw

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
they claw people, they don't bite people

:cl:
- tweak: Changed xeno melee effect into a red claw.

### CODE REVIEW

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Is it possible to make this red like 13? At least when attacking marines

**Comment by Dutch-VanDerLinde** [comment]
> Is it possible to make this red like 13? At least when attacking marines

I guess but that would need some code

**Review by QuietlyWhisper — DISMISSED** [review]
Basic change is fine add color after

**Comment by DrSmugleaf** [comment]
> > Is it possible to make this red like 13? At least when attacking marines
> 
> I guess but that would need some code

Should be able to just parent the claw entity and then sprite color red

**Comment by Dutch-VanDerLinde** [comment]
https://github.com/user-attachments/assets/2ca8646a-9a33-434e-b993-983f3ace6f39

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
