### PR TITLE
added Xeno Energy Alert

### PR DESCRIPTION
**Pull request by Kolakolanikolay**
Completely by analogy with plasma alarm, I made the same thing, only for the energy of xeno (for kamikaze runner and warden Praetorian).
Now they will be able to clearly track the amount of their energy.
The plasma system was also slightly modified. So that the alert does not appear when the target does not have plasma (plasmaMax==0). 
It will be useful for the same acid runner. Now he will have a single alert associated with his energy reserve.

### CODE REVIEW

**Comment by Rainbeon** [comment]
1) These are called Alerts, not Alarms

2) Test fail is related, please fix and make sure it runs

3) Please include a video demonstration of it working

**Comment by Kolakolanikolay** [comment]
fixed, I also attach a video demonstration

https://github.com/user-attachments/assets/32464d85-b21e-4184-8f64-1aa866086484

**Comment by Vermidia** [comment]
If possible could you have a way to have custom names and descriptions? Aciders energy is called acid reserves, Warden's health reserves etc, they usually aren't called energy by abilities and such.

**Comment by Kolakolanikolay** [comment]
It sounds logical. The only solution I found would be to create a new alert for each case. Added.

**Comment by Kolakolanikolay** [comment]
https://github.com/user-attachments/assets/858c436f-1686-4491-957e-38cbe91f8e24

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
