### PR TITLE
Fix RMC admin actions transforming into gardener instead of base drone

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

Attempting to transform into a drone through the RMC admin actions menu transformed the target into the gardener drone instead of the regular drone. This PR fixes that.

## Why / Balance

Bug fix

## Technical details

Commented out an unfinished prototype

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Why does the same bug not happen with the warden strain?

**Comment by Rainbeon** [comment]
I don't think we need Changelog here as the Gardener Drone isn't released yet, so no player-facing change is made here

**Comment by Dutch-VanDerLinde** [comment]
> I don't think we need Changelog here as the Gardener Drone isn't released yet, so no player-facing change is made here

gardenerer was mreged right?

**Comment by Rainbeon** [comment]
> > I don't think we need Changelog here as the Gardener Drone isn't released yet, so no player-facing change is made here
> 
> gardenerer was mreged right?

It's merged but not live so normal players don't experience this and thus have no need to be notified of it being fixed, it's similar in effect to a bug being fixed in the original before its merged

**Comment by crystalHex** [comment]
So uh, turns out this was entirely on me. I added an unfinished prototype for the healer to test out lesser resin fruit (and to make sure whoever ports it has the fruit ability working correctly), but didn't add it as a viable strain for the drone (due to it not being finished). Commenting it out also fixes the issue.

**Pull request merged**
