### PR TITLE
Adds bouqets

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR

Adds a lily, rose, and poppy bouqet.
## Why / Balance

It'd probably look nicer ingame than just the single poppies. 
## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Hyenh** [comment]
Man, I do not understand these build failures

**Comment by Vermidia** [comment]
my bad, I messed up a thing elsewhere

**Comment by Hyenh** [comment]
image

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
