### PR TITLE
Turns every greenified medical sprites into a sweeter blue

### PR DESCRIPTION
**Pull request by UnicornOnLSD**
## About the PR

Modified every sprite with a red cross that were touched in #2690 and #2764, going from green to a sweeter blue. Matching overall, medical aspect more.
Main issue that was raised by Whipser was that, I quote: "Blue conflicts with the CO and high command ranks on some ert", I tried to address it by keeping the blue away from said CO, see media.

I did it for the sake of it, if unsure about how it goes, it would be possible to try that out before people get used to this green further.

## Why / Balance

I probed community opinion on the discord and generally, find the blue icon for medical more appealing than green, of course none of this is "better" than the green, I,among other people find it fits better.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Before: 
image
After:
image
Comparaison with CO:
image

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Can you also change all the colors of the floor tiles used in medbay from green to blue so we have one consistent color? That's another reason I was against it, but I think I'll put this up to community poll and we'll see which color is prefered.

Make sure to include a screenshot of savannah medbay so everyone can see what the changes look like in game.

Also make sure to update the copyright source on the .RSI files.

**Comment by QuietlyWhisper** [comment]
also another good feedback
image

**Comment by UnicornOnLSD** [comment]
>Can you also change all the colors of the floor tiles used in medbay from green to blue so we have one consistent color? That's another reason I was against it, but I think I'll put this up to community poll and we'll see which color is prefered.

Seeing the general tendency I'll get on that

>Also make sure to update the copyright source on the .RSI files.

So you want me to change the copyright link on every .rsi file i've edited so far to the ones for the green icons, is what I'm getting ?

**Comment by UnicornOnLSD** [comment]
>also another good feedback (the glasses doctors have)

Will change the medhuds, yeah

**Comment by UnicornOnLSD** [comment]
done, here's what you ordered 
image

Now personally it doesn't bother me THAT much, but generally the dark green here works for the entire medical sprites.

I was aiming to just touch the greenified stuff to blue, because those don't impact AS much and were originally red, if we keep going that round I might as well blueify the rest.

My thought process would be to keep the stuff I edited today green, and just keep job icons and the few ACTUAL DMCA stuff blue, rest can stay green, up to you.

**Comment by UnicornOnLSD** [comment]
TL:DR as I see it, we don't touch the tiles but medhud and everything else we do, it'll look good for corpsmans (that but fully BLU )
image

As it'll just be the HUD. Then I'll have to change with it the RSI for other jobs that spawn with a medhud. All up to you boss

**Comment by UnicornOnLSD** [comment]
note for self: if we do scrap the tiles it's all fine, if not change tile name accordingly for almayer

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Talked with Whisper, medbay tiles should be reverted back to green. Everything else is fine, thanks for the PR!

**Comment by UnicornOnLSD** [comment]
Will nuke this PR and make a new one for convenience's sake, cheers.

**Pull request closed without merging**
