### PR TITLE
removes problematic last name

### PR DESCRIPTION
**Pull request by Kadeo64**
## About the PR
removed an unfunny, most certainly RP inappropriate last name
## Why / Balance
'hujsak' come on
if upstream finds this name bad then rmc14 will most certainly find it bad
https://github.com/space-wizards/space-station-14/pull/32998
## Technical details
updated last.yml
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by MediaResAchaea** [comment]
i mean it's fine to remove the name because players are children but this is a real polish last name :P

**Comment by Rainbeon** [comment]
Wont that upstream PR just naturally flow downstream next time we pull from them

**Comment by Kadeo64** [comment]
> Wont that upstream PR just naturally flow downstream next time we pull from them

i don't remember the last time we pulled from upstream i thought we were behind on a lot of things (edit: turns out i'm stupid and the most recent upstream changelog on rmc14 is 10/10?? i could have sworn we were behind by like a month)
i'll close this if we're pulling from upstream soon

**Review by DrSmugleaf — APPROVED** [review]
I'll just merge this now so I don't forget, should be fine merge conflict wise

**Pull request merged**
