### PR TITLE
SEA Vendor Update

### PR DESCRIPTION
**Pull request by PursuitInAshes**
## About the PR
The SEA uniform vendor now has the option for the service jacket, ballistics vest, medkit pouch.
The SEA Weapon Vendor now has the reddot sight.

## Technical details
YAML Updating.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: The SEA vendors have been updated to include new items and equipment: Service Jackets, medkit pouch, reddot sight.

### CODE REVIEW

**Comment by Vermidia** [comment]
Almayer is supposed to have training nades in the firing range. That's why there isn't any in the vendor.

**Comment by PursuitInAshes** [comment]
> Almayer is supposed to have training nades in the firing range. That's why there isn't any in the vendor.

Aye. I believed that was the case, but even then I do believe it best that SEAs have a consistent way of getting training grenades.

**Comment by PursuitInAshes** [comment]
The Ubuntu fail seems unrelated.

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
SEA are meant to be given a MK1 rifle (not the basic m54c) which is not implemented yet, which is why the vendor doesn't contain a bipod.

The SEA if they would like a different weapon should be issued one by requisitions, though per SOP they would have to keep those weapons stored in their office anyway, unless the SEA is deploying. There's no reason they should be assigned whatever weapon they want otherwise.

If an SEA is "stealing" weapons they probably shouldn't be a whitelisted SEA. These roles are expected to follow marine law and SOP the same.

**Review by QuietlyWhisper — APPROVED** [review]
Thanks

**Pull request merged**
