### PR TITLE
Added shoulder holster

### LINKED ISSUE #651: Shoulder Holster

### LINKED ISSUE #973: Shoulder Holster Crate (x4) Cost: $2000

### LINKED ISSUE #1413: 15P Shoulder Holster

### LINKED ISSUE #1542: Shoulder Holster

### LINKED ISSUE #1596: Shoulder Holster

### LINKED ISSUE #1717: Shoulder Holster

### LINKED ISSUE #1832: Shoulder Holster

### LINKED ISSUE #1889: Shoulder Holster

### LINKED ISSUE #1968: Shoulder Holster

### LINKED ISSUE #2259: 1 Shoulder Holster

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

Added the shoulder holster

## Why / Balance

CM13 parity
Resolves #651, resolves #973, resolves #1413, resolves #1542, resolves #1596, resolves #1717, resolves #1832, resolves #1889, resolves #1968, resolves #2259 

## Technical details

Sprites ported from CM13
Uses the system added in #4522, the only modification being increased priority for the unholster verb to prioritise unholstering over folding jackets

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the shoulder holster.

### CODE REVIEW

**Comment by crystalHex** [comment]
Progress update:
- icon and worn sprite are ported
- the holster can store a sidearm and two sidearm magazines
- the holster can be attached to uniform
- quick holster/unholster keybinds work
- clicking on the holster with a gun holsters it; alt-clicking unholsters it, but only when it's not attached to a uniform
- right clicking on uniform displays verb for unholstering gun, if one is holstered

Still to do:
- allow for guns to be holstered by clicking on the uniform that has an attached holster (in progress)
- allow for guns to be unholstered by alt-clicking on the uniform
- add the holster to vendors

**Comment by crystalHex** [comment]
Updated this to match the updated holster system. The shoulder functions identical to the belt holsters, except as a webbing.

**Comment by crystalHex** [comment]
Screenshot of the shoulder holster:
image

Screenshot of the surplus uniform vendor (as an example):
image

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
