### PR TITLE
Remove fire delay from guns when you switch hands

### LINKED ISSUE #4088: Gun delay is too high
In CM, it's almost instant to equip and begin shooting a gun, but here it takes like 3 seconds

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
In CM13 you can dual wield like this:

https://github.com/user-attachments/assets/7ef65909-b47a-4148-9c05-a7ffddb23a51

currently, this isn't possible, because there's a cooldown

resolves #4088

I disabled the "resetOnHandSelected" datafield in this PR
also gave a melee sound for the gun

### CODE REVIEW

**Comment by DogZeroX** [comment]
What if you just make it a mechanic instead of relying on wacky x spam so you can add penalty to or something

**Comment by Dutch-VanDerLinde** [comment]
> What if you just make it a mechanic instead of relying on wacky x spam so you can add penalty to or something
I dont understand

**Comment by DogZeroX** [comment]
Add an action or button to dual-wield instead of having to swap hand spam

**Comment by Vermidia** [comment]
You can see in the shot that cm already makes both guns fire if you have them in both hands. I believe it comes with a heavy hit to accuracy and or scatter.

**Comment by DogZeroX** [comment]
I can't see that, I just see the hands quick-swapping which looks silly

**Comment by MACMAN2003** [comment]
THERE WAS A DELAY THIS WHOLE TIME?!! I THOUGHT IT WAS JUST PING

**Comment by Dutch-VanDerLinde** [comment]
> You can see in the shot that cm already makes both guns fire if you have them in both hands. I believe it comes with a heavy hit to accuracy and or scatter.

theres still not supposed to be a delay anyway, messes up with picking up dropped guns

**Comment by Kadeo64** [comment]
MAX PAYNE

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Comment by k0r4y** [comment]
https://github.com/user-attachments/assets/1162a7e3-1ff2-485e-8c7f-2ba90326c1e6

just putting this here, not sure if this is an intended mechanic of this change, seems a bit overpowered with shotguns

**Comment by Vermidia** [comment]
Yeah we need fire group delays, so you can't fire another shotgun after firing a shotgun. It's mainly specifically for to prevent juggling.

**Pull request merged**
