### PR TITLE
Magazine box deconstruct

### PR DESCRIPTION
**Pull request by ShadowCommander**
## About the PR

Add deconstructing magazine boxes into cardboard.

## Technical details

Fixes SpawnPrototype spawning items attached to the player.

---

This adds a new ConstructionGraphStep type: `InteractionGraphStep` that allows for advancing a construction graph without using a material or tool.

The construction step advances when the entity receives a `ConstructionInteractionEvent`. This code sends a `ConstructionInteractionEvent` when a verb is pressed in `ConstructionInteractionVerbSystem`.

---

Added a ConstructionGraphCondition `RMCItemSlotsEmpty` that checks whether all the entities ItemSlots are empty.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/RMC-14/RMC-14/assets/10494922/2499038c-8311-465d-af04-104901daf81c

## Breaking changes

**Changelog**

:cl:
- add: Magazine boxes can now be deconstructed into cardboard using the fold box verb.

### CODE REVIEW

**Comment by Skarletto** [comment]
remove the doafter and then bingo

does this work if the box is not placed? and can you altclick it / activate in hand to fold it?

**Comment by ShadowCommander** [comment]
It works anywhere as long as the box is empty. When I asked in Discord, I was told to only make it a verb.

Currently:
- ActivateInHand deploys the box on the ground.
- Alt+Interact doesn't do anything when empty, but if there are magazines, it pulls one out.

**Comment by Skarletto** [comment]
> I was told to only make it a verb.
a

**Comment by DrSmugleaf** [comment]
Linter is failing
```
Error: /Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml(296,9)  Field "interaction" not found in "Content.Shared.Construction.Steps.InteractionGraphStep".
```

**Comment by ShadowCommander** [comment]
Fixed, though kinda hacky since the value is unused.

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Is it possible to use a new component for this? There are quite a few upstream changes when we just need to be able to fold boxes, which should be doable with a component and system with a few dozen lines of code.
I think the flexibility is nice but this should probably be upstreamed in case upstream wants it if you want to bother. Otherwise for our case it would be better as a new component and system in its own separate files.

**Comment by ShadowCommander** [comment]
Are merge conflicts a big problem? I made it in construction because i wanted to upstream it soon too.

Just want to know whether to do upstream merge first or here first.

**Comment by DrSmugleaf** [comment]
> Are merge conflicts a big problem? I made it in construction because i wanted to upstream it soon too.
> 
> Just want to know whether to do upstream merge first or here first.

Upstream first but if you want it to get merged here quickly as well you could do it with a separate component/system, unless you really want to keep it as part of construction system.

**Comment by ShadowCommander** [comment]
Closing until upstream stuff is merged. Until then #2855 implements similar functionality.

**Pull request closed without merging**
