### PR TITLE
Add visual damage states for xenos

### PR DESCRIPTION
**Pull request by DrSmugleaf**
## About the PR
I forgor to PR this

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Xenonids will now get visibly injured from damage.

### CODE REVIEW

**Comment by Sionnach86** [comment]
@DrSmugleaf Hi there! I recently joined RMC recently! 

I was the one who did the original 'bleeding' pixel art for CM13. I *still* have my pixel art assets we used if that is of any interest. :)

I was directed her from folks on the Discord!

**Comment by DrSmugleaf** [comment]
> @DrSmugleaf Hi there! I recently joined RMC recently!
> 
> I was the one who did the original 'bleeding' pixel art for CM13. I _still_ have my pixel art assets we used if that is of any interest. :)
> 
> I was directed here from folks on the Discord!

@Sionnach86 oh that would be useful ty, is it for the xenonid sprites? The ones I found for them on the 13 repo didn't seem to match their alternate sprites but I might have been doing something wrong
If you have them though we could use them if they are also licensed under cc by sa 3.0 or similar

**Comment by DrSmugleaf** [comment]
@Sionnach86 I'm going to merge this for the update tonight, but if you have the xenonid wound sprites ping me on the Discord with them
I added a note for you being the author to the wounds.rsi

**Comment by Sionnach86** [comment]
> @Sionnach86 I'm going to merge this for the update tonight, but if you have the xenonid wound sprites ping me on the Discord with them I added a note for you being the author to the wounds.rsi

Got it! I likely will have to tinker with the sprites - this will be a few days! Saw the PR's in working order! I'll let you know when the sprite work is adjusted!

**Pull request merged**
