### PR TITLE
Adds Tucking features in

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

You can now tuck in hair/frills/horns/antenna/some diona stuff/cat ears into your helmet

Also fixed felenids not having an undershirt by default (smol)

## Why / Balance

CM-13 parity, rp things.

## Technical details

Uses the foldable system since it had mostly everything I needed. It doesn't come with messages unfortunately like cm-13. Also added hidelayersonequip to species that needed them for this.

Small note that the folable clothing system has a bug where if you fold while worn, it doesn't actually update the clothing state. This allows you to for instance have your hair/antenna disappear if you tuck it in, put it on, and untuck while it's on, then take it off.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/a57492ac-5f90-4b71-8e95-5968b70faec7

## Breaking changes

no?
**Changelog**

:cl:
- add: You can choose to tuck in features (like hair, moth antenna, etc) on helmets.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
Can you make it hide HeadSide too

**Comment by QuietlyWhisper** [comment]
Pretty sure it does

**Comment by QuietlyWhisper** [comment]
you might also have to add this to basic helmets which has the riot gear I think

**Comment by Dutch-VanDerLinde** [comment]
Make BaseRMCHelmet which has the tucking in features

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
