### PR TITLE
Port CM mapping signs

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
For mapping use

### CODE REVIEW

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Thanks for the PR!

ice_sign, laz_sign, sorokyne and sorokyne_1 need to be changed in some form to remove copyrighted material

**Comment by Dutch-VanDerLinde** [comment]
> Thanks for the PR!
> 
> 
> 
> ice_sign, laz_sign, sorokyne and sorokyne_1 need to be changed in some form to remove copyrighted material

how are they copyrighted?

**Comment by Tunguso4ka** [comment]
> how are they copyrighted?

Weyland-Yutani logo.
The yellow W

**Comment by Dutch-VanDerLinde** [comment]
Removed the weyland yunati logo

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
