### PR TITLE
Adjusted tail stab damage to parity.

### PR DESCRIPTION
**Pull request by Binbagg**
## About the PR

changed tailstab damage to be parity damage for each xeno caste
values fixed, runs
## Why / Balance
parity
## Technical details
yaml

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

:cl:
- tweak: Adjusted tail stab damage to be parity

### CODE REVIEW

**Comment by Binbagg** [comment]
right mate

**Comment by Binbagg** [comment]
apparently smug will fix merge conflicts, so fine to do...... Erm

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR, but please do not make a new one, it makes it more difficult to check old reviews

**Comment by Binbagg** [comment]
okay

**Pull request merged**
