### PR TITLE
Added shotgun shell boxes 

### PR DESCRIPTION
**Pull request by CyberTropic**
## About the PR

Added cases for handfuls of shotgun shells. Ordering from req now gives you 1 case containing 20 handfuls. The cases function the same way as other ammo boxes in the game.

## Why / Balance

Parity

## Technical details

Just YML

## Media

All shell handful types:
cap1
cap3
However the unfinished ammo types aren't craftable yet, so it's just commented out:
cap4
pov you're in req:
cap2

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added magazine boxes for handfuls of shotgun shells.

### CODE REVIEW

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Handfuls are implemented now so this can use them, should be 20 handfuls per box

**Comment by CyberTropic** [comment]
PR changed to use the new handfuls of shells

**Review by DrSmugleaf — APPROVED** [review]

**Comment by DrSmugleaf** [comment]
Two test fails are real
```
  Error Message:
     Found no startNode "RMCBoxShellsIncendiaryEmpty" on graph "RMCBoxMagazine" for entity "RMCBoxShellsIncendiary"!
```

```
   System.Collections.Generic.KeyNotFoundException : The given key 'RMCBoxShellsIncendiaryEmpty' was not present in the dictionary.
```

**Comment by CyberTropic** [comment]
> Two test fails are real
> 
> ```
>   Error Message:
>      Found no startNode "RMCBoxShellsIncendiaryEmpty" on graph "RMCBoxMagazine" for entity "RMCBoxShellsIncendiary"!
> ```
> 
> ```
>    System.Collections.Generic.KeyNotFoundException : The given key 'RMCBoxShellsIncendiaryEmpty' was not present in the dictionary.
> ```

Ah, since construction is commented out, they shouldn't be listed as constructable if spawned in for whatever reason

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
