### PR TITLE
USS LCS-14 Savannah: Rework

### LINKED ISSUE #2132: Savannah needs more weapon vendors in each squad room

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

*slaps png image* This baby is better then previous one by 3.50%.

Fully reworked Savannah, based on the cmss13 Almayer and TGMC Theseus.
- Better engi (previous iteration was shit)
- Better prep (previous was shit)
- Better med (now with surgery)
- Toilets!
- Fancy Liaison office
- Better sec (previous was great too, but hear me out)
- Dirt
- todo cm14 make more todos

Currently it lacks all kinds of decorations and small items, but it will be solved in the next PRs.

Closes #2132 

## Media

зображення

Savannah-0
idk why, but maprenderer inverts tiles.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
looks very good so far

**Comment by QuietlyWhisper** [comment]
I'll review this a bit later so we can focus on other things

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
I think the WY logo would look better the correct side up since it would always be viewed at that angle

and, same as with Solaris,

Remove all cable wiring, use always powered lights. don't worry about reporting unpowered devices for now, thanks!

You should be able to remove them / replace them within the yml file

**Comment by Tunguso4ka** [comment]
> I think the WY logo would look better the correct side up since it would always be viewed at that angle
> 
> and, same as with Solaris,

Thats the MapRenderer problem. Idk why, but it inverts tiles. There an image somewhere in #mapping with ingame screenshot of Savanna's CL room.

**Comment by Tunguso4ka** [comment]
> Thats the MapRenderer problem. Idk why, but it inverts tiles. There an image somewhere in #mapping with ingame screenshot of Savanna's CL room.

зображення

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Only one of these per squad should be mapped
image

Replace these anywhere with hull wall due to how cm14 works people can just walk outside
image

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
For dropship landing spots we use CMDropshipDestination instead of FTL points, that will also fix the test error. Also feel free to place a couple CMDropshipHijackDestination around wherever you want the dropship to crash into upon hijack. It's a placeholder right now until we get areas, but the Queen can choose from one of those when interacting with a dropship navigation computer.

**Comment by Tunguso4ka** [comment]
> For dropship landing spots we use CMDropshipDestination instead of FTL points

done. And... i was asking for a help with Solaris...

**Comment by Tunguso4ka** [comment]
We probably need to remove/disable test for docking
`Unable to dock /Maps/Shuttles/emergency.yml to Savannah`

**Comment by DrSmugleaf** [comment]
> > For dropship landing spots we use CMDropshipDestination instead of FTL points
> 
> done. And... i was asking for a help with Solaris...

Oops, I'll review it in a sec

> We probably need to remove/disable test for docking `Unable to dock /Maps/Shuttles/emergency.yml to Savannah`

I'll look into this too

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
The map looks good, try to add two or three more hijack destinations so marines can't always know where the ship will crash and then we merge

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Just learned from brazil fork that there are medical vendors in the corpsmen rooms, they don't have access to these machines because they're intended to be used for medical, so medics do not take all their medicine.

Medics have tons of points to buy medicines and tools at their own vendors, this is not needed. Thanks!

I was also told the same applies for the tool vendors mapped in comtech rooms

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
This shouldn't be mapped into combat tech room, they get tools from their belt for free, this just creates more flare packs for free
image

I'm pretty sure these are also only intended to be mapped into medical despite the name, the items it contains are available to be bought in the medic vendors or are free
image

**Comment by QuietlyWhisper** [comment]
Map looks good but the podlocks aren't airtight and need to be fixed by the way

**Review by QuietlyWhisper — DISMISSED** [review]

**Comment by Tunguso4ka** [comment]
> Map looks good but the podlocks aren't airtight and need to be fixed by the way

but we dont have atmos turned on.

**Comment by Tunguso4ka** [comment]
Almayer still uses old Savannah btw.

**Comment by QuietlyWhisper** [comment]
> Almayer still uses old Savannah btw.

YML file is still loaded, not sure what's wrong with the actual savannah though

**Comment by Tunguso4ka** [comment]
> YML file is still loaded, not sure what's wrong with the actual savannah though

Build and Test Debug is failed because game checks if it possible to dock evacuation shuttle to the station, with is not possible because I removed shuttle docks.

**Comment by QuietlyWhisper** [comment]
Smug will try to fix emergency shuttle test

**Comment by QuietlyWhisper** [comment]
It should not be testing for evac shuttle because the component is removed as far as I know

**Review by QuietlyWhisper — APPROVED** [review]
Smug said to merge and will test it on master

**Pull request merged**
