### PR TITLE
ASO playtime now counts as command, CO playtime now counts as military police

### PR DESCRIPTION
**Pull request by AverageNotDoingAnythingEnjoyer**
## About the PR

Now commanding roles playtime takes ASO playtime into account, and MP playtime takes CO playtime into consideration

## Why / Balance

It's parity, as seen in https://github.com/cmss13-devs/cmss13/blob/a7f65c8ba7ceff1a55b7489d5baae2700d9d3bb1/code/__DEFINES/job.dm#L4, lines 82 and 99

## Technical details

Made a separate JobGroup for MP and Command, which include all of the specific department roles, plus CO and ASO respectively

## Media

Screenshot 2024-12-15 at 03 59 53
Screenshot 2024-12-15 at 04 00 13

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: J C Denton
- tweak: Commanding roles playtime now includes ASO playtime, Military Police playtime now takes into account CO playtime.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
conflicts with 
- #3751

**Review by QuietlyWhisper — COMMENTED** [review]
See conflicts with the comment I posted, also, new IDs should be RMC and not CM

I also do not want ASO playtime to contribute to CO requirements, and the military police requirements have already been changed per the existing PR

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
> See conflicts with the comment I posted, also, new IDs should be RMC and not CM
> 
> I also do not want ASO playtime to contribute to CO requirements, and the military police requirements have already been changed per the existing PR

So uh, shall I fix the conflicts or is this a 'no parity' case?

**Comment by Dutch-VanDerLinde** [comment]
so can CO counting as MP role be PR'd or no

**Pull request closed without merging**
