### PR TITLE
Add medical kit pouch to vendors

### LINKED ISSUE #779: ColMarTech Squad Medical Gear Rack
MEDICAL SET (MANDATORY)
- [x] #1722

---

FIELD SUPPLIES
- [x] #1723
- [x] #1724
- [ ] #1725
- [x] #1726
- [x] #1727
- [x] #1728

---

 FIRSTAID KITS
- [x] #1729
- [x] #1730
- [x] #1731
- [x] #1732
- [x] #1733
- [ ] #1734

---

AUTOINJECTORS
- [x] #1735
- [x] #1736
- [x] #1737
- [x] #1738
- [x] #1739
- [ ] #1740
- [ ] #1741
- [x] #1742

---

PILL BOTTLES
- [x] #1743
- [x] #1744
- [x] #1745
- [x] #1746
- [x] #1747
- [ ] #1748
- [ ] #1749

---

MEDICAL UTILITIES
- [x] #1750
- [x] #1751
- [x] #1752
- [x] #1753
- [x] #1754
- [ ] #1755

---

EXPLOSIVES
- [x] #1756
- [ ] #1757
- [ ] #1758
- [x] #1759
- [ ] #1760
- [ ] #1761
- [ ] #1762
- [ ] #1763
- [ ] #1764

---

PRIMARY AMMUNITION
- [x] #1765
- [x] #1766
- [x] #1767
- [x] #1768
- [x] #1769

---

SIDEARM AMMUNITION
- [ ] #2245
- [x] #2246
- [ ] #2247
- [ ] #2248
- [x] #2249
- [x] #2250

---

ARMORS
- [x] #1770
- [x] #1771

---

 RESTRICTED FIREARMS
- [x] #1772
- [x] #1773

---

CLOTHING ITEMS
- [x] #1774
- [x] #1775
- [x] #1776
- [ ] #1777
- [ ] #1778

---

UTILITIES
- [x] #1779
- [x] #1780
- [x] #1781

---

BINOCULARS
- [x] #1782
- [x] #1783
- [x] #1784

---

HELMET OPTICS
- [ ] #1785

---

PAMPHLETS
- [x] #1786
- [x] #1787

---

RADIO KEYS
- [x] #1788
- [x] #1789
- [x] #1790
- [x] #1791

### LINKED ISSUE #1822: Medical Kit Pouch

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Adds the medical kit pouch with the skill requirement (using the technology from pill canisters).

## Why / Balance

CM-13 parity, we have the technology (Also the message in CM-13 just says you can't get/put stuff in there but can still open it?? It's close enough anyway)
Fixes #1822, fixes #779

## Technical details

YML

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

nu
**Changelog**

:cl:
- add: Added medical kit pouch to corpsman gear rack and requisitions.

### CODE REVIEW

**Review by DrSmugleaf — COMMENTED** [review]
Was this all that was missing? I know I told Tunguso4ka not to add it to the vendor since we didn't have the "medical skill to use it effectively" thing but I thought that was something other than just being able to use it at all

**Comment by Vermidia** [comment]
I think that's all but I'll ask in the discord just in case.

**Comment by Vermidia** [comment]
Ok, I can't really do the take stuff out but can't put stuff back in without changing a lot of storage so the id lock that the pill uses will have to do for now.

**Comment by DrSmugleaf** [comment]
I'll try to implement something for this later

**Comment by Vermidia** [comment]
Added the new component to this and it seems to work right! Just needed to define the whitelist twice.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
