### PR TITLE
Fix GunDamageModifier

### PR DESCRIPTION
**Pull request by snebl**
## About the PR

The assault rifle, battle rifle, and other weapons that use the `GunDamageModifier` component should now deal the correct damage.

## Why / Balance

Fixes [#2646](https://github.com/RMC-14/RMC-14/issues/2646).

## Technical details

Basically calls `RefreshGunDamageMultiplier` when a gun spawns in and not just when something attaches to it.
No clue what i'm doing for the most part but it seems to work without error. I'm sorry if i have committed some kind of sin here, i have never touched ss14 code before.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed damage modifiers not being applied on marine firearms.

### CODE REVIEW

**Comment by Siigiil** [comment]
This will fire every time a gun shoots. So every time every marine gun shoots, it'll recalculate this modifier.
Would be better to just subscribe to `MapInitEvent` and do it there. That way it will only fire once, when the gun spawns in. And then whenever the relevant attachments are modified.

**Comment by snebl** [comment]
@Siigiil Like this?

**Comment by Siigiil** [comment]
> @Siigiil Like this?

Yes.

**Review by QuietlyWhisper — APPROVED** [review]
Thanks

**Comment by snebl** [comment]
image

**Pull request merged**
