### PR TITLE
Almayer is now fallback map, added Almayer to default map pool

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

- Added `fallback: true` to Almayer proto
- Removed `fallback: true` from Saltern proto
- Added Almayer to Default Map Pool
- Changed minPlayers from 0 to 90 on Almayer

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
I tried making savannah fallback, setting savannah min pop to 50 to force almayer to be picked but it still falls back to savannah so something must be wrong with almayer

**Comment by QuietlyWhisper** [comment]
image
???

**Comment by QuietlyWhisper** [comment]
it might just be because almayer is secretly savannah and I'm getting gaslit so I'll try more tests

**Comment by QuietlyWhisper** [comment]
That should be enough info for smug to look into it at least

**Review by DrSmugleaf — APPROVED** [review]
saltern major victory

**Pull request merged**
