### PR TITLE
Give CMO + ASO more comms

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Title.

## Why / Balance

CM-13 parity, they were given squad + engi comms to match other command.

ASO was missing theres

## Technical details

YML

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

no
**Changelog**

:cl:
- add: CMO now has squad and engi comms

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
why does the cmo get squad comms but not the aso

**Comment by vorkathbruh** [comment]
> why does the cmo get squad comms but not the aso

ask in the cm-ss13 github

**Comment by Vermidia** [comment]
ASO should have squad coms?

```
/obj/item/device/encryptionkey/mcom/alt
	channels = list(RADIO_CHANNEL_COMMAND = TRUE, SQUAD_MARINE_1 = FALSE, SQUAD_MARINE_2 = FALSE, SQUAD_MARINE_3 = FALSE, SQUAD_MARINE_4 = FALSE, SQUAD_MARINE_5 = FALSE, SQUAD_MARINE_CRYO = FALSE, RADIO_CHANNEL_ENGI = TRUE, RADIO_CHANNEL_MEDSCI = TRUE, RADIO_CHANNEL_REQ = TRUE, RADIO_CHANNEL_JTAC = TRUE, RADIO_CHANNEL_INTEL = TRUE)
```

**Comment by Dutch-VanDerLinde** [comment]
why was there a pr to remove aso's squad comms then tf

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
