### PR TITLE
Added pickup, drop and use sounds

### LINKED ISSUE #3461: Combat boots and machete pouch need their custom sheathe sounds from CM13
current sound is very ugly

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

- Added pickup sounds for tools: Crowbar, Welders, Wrench, Multitool, Wirecutters, Screwdriver
- Added pickup sound for toolbox
- Added pickup and drop sounds for guns
- Added pickup and drop sounds for paper
- Added equip unequip sounds for armor
- Added equip unequip sounds for uniform
-  Added holster unholster sounds for boots

Checked ingame and in audacity - No stereo sounds.

Closes #3461

**Changelog**

:cl:
- add: Added pickup and drop sounds for tools!
- add: Added equip and unequip sounds for clothing!

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
YES THIS IS THE BEST PR EVER

**Comment by Dutch-VanDerLinde** [comment]
also the toolbox drop sound should play on drop and on throw, since SoundOnLand only plays when its thrown

**Comment by Tunguso4ka** [comment]
> also the toolbox drop sound should play on drop and on throw, since SoundOnLand only plays when its thrown

upstream toolbox already have the same drop sound.

**Comment by Dutch-VanDerLinde** [comment]
EmitSoundOnLand and EmitSoundOnDrop are different

**Comment by Tunguso4ka** [comment]
> EmitSoundOnLand and EmitSoundOnDrop are different

what the difference?..
They sound the same.

**Comment by Tunguso4ka** [comment]
ooohhh, i got it.

**Comment by Tunguso4ka** [comment]
> also the toolbox drop sound should play on drop and on throw, since SoundOnLand only plays when its thrown

it gonna cause too much noise.

**Comment by Dutch-VanDerLinde** [comment]
It's how it works in SS13 but thats fair

**Review by DrSmugleaf — APPROVED** [review]
bless

**Pull request merged**
