### PR TITLE
Lurker Invisibility Rework

### LINKED ISSUE #4043: Lurkers shouldn't de-cloak when hitting barricades, only marines
CM13 parity last i checked

### LINKED ISSUE #4349: Lurker Parity: Manually Cancelling Invisibility Refunds Cloak Cooldown
## Description
In CM13, Lurker can re-press the ability to toggle off their invisibility, putting it on a Cooldown proportional to the amount of time they have spent cloaked. Cancelling Invisibility requires paying the plasma cost again, as well.

**Video**
https://github.com/user-attachments/assets/e16ab0df-86f3-4cb2-ad2f-20d94527dca7

### LINKED ISSUE #4354: Lurker Parity: Lurkers can shove while invisible, but devouring ends invisibility.
## Description
In CM13, Lurkers can shove down Marines while invisible without cancelling it. However, attempting to devour instantly ends the invisibility (with some cooldown refund). This is basically the opposite of how we have it, as our Lurkers can currently devour while invisible, but not shove.

**Videos**
https://github.com/user-attachments/assets/e9f6e695-39c7-4282-bc4c-5ee548391bc7

### PR DESCRIPTION
**Pull request by Rainbeon**
## About the PR
Entirely reworks Lurker Invisibility to match CM13

- [X] Cloak doesn't end when hitting structures and non-enemies
- [X] Shoving doesn't break cloak
- [X] Manual Cloak Deactivation, refunds 90% Cooldown based on cloak time
- [X] Devour attempt breaks cloak and refunds 50% Cooldown based on cloak time

## Why / Balance
CM13 Parity. Lurker needs the love.

Resolves #4043 
Resolves #4354 
Resolves #4349

## Technical details
- Changes the MeleeAttack check to a MeleeHit check, only de-cloaking if they hit an enemy mob. This also correctly enables shoving Marines while cloaked.
- Added GetRefundedCooldown() and StartCooldown() as helper functions as the code is re-used several times. The refunded cooldown function is 1:1 to with CM13 (though they calculate time from start, while we calculate time until end)
- Included RemCompDeferred in RemoveInvisibility() as well as the Popup Handling.
- RemoveInvisibility() now takes a TimeSpan cooldown, which it passes to StartCooldown()
- Now tracks DoAfterAttemptEvent for XenoDevourDoAfterEvent, and instantly ends your cloak once you start for 50% refunded cloak.
- Added a short lockout timer to cloaking to prevent double-hits (cm13 parity).
- TurnInvisibleComponent now holds the Lockout Timer, and both Manual and Revealed Refund Multipliers.
- StartCooldown now accepts toggledStatus as a bool for the action bar visuals.
- No more args.Handled as we manually set variable cooldowns.

## Media
Full Demonstration
https://github.com/user-attachments/assets/2de55c19-ea1d-414c-8d3d-6d50f48ffdd4

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Lurkers can now manually toggle off their invisibility, which refunds 90% of the remaining cloak time.
- add: Lurkers can now attack structures and wideswing without losing invisibility, as long as they do not hit a Marine.
- add: Lurkers can now shove Marines without losing invisibility.
- remove: Lurkers can no longer devour while invisible. Doing so de-cloaks them and refunds 50% of the remaining cloak time.

### CODE REVIEW

**Comment by Kadeo64** [comment]
secret lurker technique is real?????

**Comment by Rainbeon** [comment]
This is almost finished, things left to do:
- Port partial CD formula from CM13 (easy)
- Figure out why handling args makes SetCooldown just not function at all or just ignore that (needs Smug input)
- Polish/Localization because I shitcoded a little bit trying to figure out point 2

**Comment by Kadeo64** [comment]
it's gonna be fun to invisible duel a scout spec

**Comment by Rainbeon** [comment]
Okay now just need the CD formula, I don't think args.Handled is necessary here since this doesn't use UseDelay at all?

**Comment by Rainbeon** [comment]
It's ready

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
