### PR TITLE
Matching parasite sprites

### LINKED ISSUE #2882: The sprite for a parasite on a marine does not match with the parasite's sprite
## Description
image

image

comparison

The sprites are different style, the facehugged marine sprite looks like a classic hugger while the actual sprite is unique

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR

- Requires #3334
Changed hugged sprite to better match the actual parasite sprite.
## Why / Balance

- fixes #2882
## Media

Before:
image
After:
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:Hyenh

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
conflicts with #3334, and also you should change the corgi and corgi puppy sprites

**Comment by Hyenh** [comment]
Forgot how this works, I'll just wait until #3334 is merged

**Review by QuietlyWhisper — DISMISSED** [review]

**Comment by QuietlyWhisper** [comment]
Smug wants to review this as well

**Comment by Dutch-VanDerLinde** [comment]
why does this remove the corgi sprites

**Comment by Dutch-VanDerLinde** [comment]
@Hyenh you should make it have a closed eye instead of open because thats how it is in the impregnated spirte
image

**Comment by Dutch-VanDerLinde** [comment]
maybe make a closed eye socket, but looks good tho

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
