### PR TITLE
Unbloated Pouches, Nuked Catalog/Fills/pouches.yml

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

- Unbloated Pouches to 4 files: `base.yml`, `storage.yml`, `weapons.yml`, `medical.yml`
- Added comments and spacing to make it look a little bit more readable.
- Nuked `Catalog/Fills/pouches.yml`
- Renamed base pouches to RMC standard. (cant rename all of them because it will break maps :\ )

### CODE REVIEW

**Comment by deltanedas** [comment]
why not rename and migrate

**Comment by Tunguso4ka** [comment]
> why not rename and migrate

too much migrates.

**Comment by Tunguso4ka** [comment]
fuck it, we ball.

**Review by DrSmugleaf — APPROVED** [review]
ty boss

**Pull request merged**
