### PR TITLE
Port command clothing, eyewear, formal uniforms, and faction clothing

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

Ported the following clothing items:
- three sets of dress blues uniforms
- two dress blues head covers
- general's uniform and jacket
- general's armored cap
- CO's white beret
- personal shades
- aviator shades
- marine operations uniform (for officers)
- officer cap
- two peaked caps
- XO's formal uniform + jacket
- four provost uniforms
- special agent uniform
- marine recon uniform (for survivors)
- MARSOC uniform
- We-Ya commando and two 'corporate security' uniforms
- freelancer uniform
- two Dutch's Dozen uniforms
- ten SPP uniforms
- ten sets of PMC armor
- six sets of SPP armor
- three SPP coats
- nine pieces of PMC headgear
- nine pieces of SPP headgear
- five sets of provost armor + special agent armor
- five sets of royal marine armor
- five sets of mercenary armor
- five sets of colonial militia armor
- two sets of PMC riot control armor
- two sets of PMC CBRN armor
- two sets of Dutch's Dozen armor
- freelancer armor
- marine raider armor
- twenty-nine pieces of headgear for other factions
- contractor uniform
- contractor synth vest
- CO's Lt.Col. and Col. berets
- squad beret

Total item count: 148

Added the ported items to the vendors where applicable
Added a version of white gloves and sunglasses with RMC-specific flavortext

This PR should include all faction armour and *most* of non-marine non-civilian uniforms and headgear.

Overview of ported items (also see images below):
image

The uniforms folder has gotten a bit crowded, so I tried to group up loose uniforms into their own folders to reduce the clutter a bit

## Why / Balance

Parity
Drip
More props for events
Progress on #3143 and #3144

## Technical details

YAML, RSI porting

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added sunglasses, personal shades and aviators to the appropriate vendors.
- add: Added five sets of uniforms and jackets, and some pieces of headgear for special occasions.
- add: Added several hats, uniforms and jackets to command vendors.
- add: Added four provost uniforms, the special agent uniform, marine survivor uniform.
- add: Added eleven uniforms for various factions for special events.
- add: Added ten sets of SPP uniforms, six sets of armor and three coats for special events.
- add: Added ten sets of PMC armor for special events.
- add: Added a total of eighteen hats/helmets for PMCs and SPP.
- add: Added another thirty sets of armor and headgear for the provost, mercenaries, colonial militia, and other factions.

### CODE REVIEW

**Comment by crystalHex** [comment]
CO's vendor:
image

XO's vendor:
image
image
image

SO's vendor:
image

**Comment by crystalHex** [comment]
The Provost and special agent uniforms:
image

**Comment by crystalHex** [comment]
image

**Comment by crystalHex** [comment]
The SPP uniforms:
image

**Comment by crystalHex** [comment]
Mercenaries
image

**Comment by crystalHex** [comment]
PMC armor:
image

**Comment by crystalHex** [comment]
SPP armors and coats:
image

**Comment by crystalHex** [comment]
PMC and SPP headgear:
image

**Comment by crystalHex** [comment]
Various faction headgear:
image

**Comment by crystalHex** [comment]
Contractor uniform and utility vest:
image

**Comment by crystalHex** [comment]
CO's berets:
image
image

**Comment by crystalHex** [comment]
The squad beret:
image

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
There are references to USCM, Armat and UA in these item descriptions, please check them over, as these factions and organizations are not in RMC.

Also, please consider splitting prs like this in the future, theyre hard to review effectively. Thank you!

**Comment by crystalHex** [comment]
Removed all references to those factions and organizations now

**Review by DrSmugleaf — APPROVED** [review]
Thnks for the PR!

**Pull request merged**
