### PR TITLE
Leadership position tracker sprites

### PR DESCRIPTION
**Pull request by noisrevni-dev**
## About the PR

- Ported CO/XO/CMP/SL/TL/CL/LZ tracker sprites.

### CODE REVIEW

**Comment by ShadowCommander** [comment]
Have you started working on the code yet? I'm actually almost done with the code on my end. Just haven't ported all the sprites.

**Comment by noisrevni-dev** [comment]
> Have you started working on the code yet? I'm actually almost done with the code on my end. Just haven't ported all the sprites.

Not yet. If you want to continue working on it, i can set this PR ready now.

**Comment by noisrevni-dev** [comment]
Done, ready for review.

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
